jump o 
look o around w left s twice x after b run o opposite v left s 
look o around w left s twice x after b run o around w left s 
run o left s twice x after b turn o left s twice x 
run o right u twice x and a look o left s thrice y 
turn o around w left s after b walk o opposite v left s twice x 
run o around w right u thrice y and a look o left s twice x 
walk o right u twice x and a look o opposite v right u twice x 
look o around w right u and a look o opposite v right u twice x 
turn o left s and a look o around w right u twice x 
walk o around w left s after b run o 
look o opposite v right u twice x after b walk o opposite v left s twice x 
jump o 
walk o opposite v left s after b turn o around w left s thrice y 
jump o 
walk o around w right u thrice y after b turn o opposite v right u thrice y 
run o left s thrice y and a turn o right u 
turn o around w right u thrice y and a turn o opposite v left s twice x 
run o around w left s thrice y after b turn o around w right u twice x 
walk o around w left s and a walk o opposite v left s thrice y 
walk o twice x and a look o opposite v right u twice x 
walk o after b run o twice x 
run o opposite v left s thrice y after b run o opposite v left s 
look o around w left s thrice y and a look o around w right u 
run o opposite v left s twice x 
look o left s thrice y and a look o right u thrice y 
turn o opposite v left s after b walk o 
walk o opposite v right u thrice y after b walk o right u twice x 
look o right u thrice y and a look o opposite v left s twice x 
run o opposite v left s after b turn o opposite v left s thrice y 
turn o opposite v right u twice x after b run o opposite v right u twice x 
walk o opposite v right u after b walk o left s twice x 
walk o opposite v left s twice x and a run o opposite v left s twice x 
jump o 
walk o opposite v right u twice x after b turn o around w right u thrice y 
run o opposite v right u twice x after b walk o twice x 
walk o around w left s after b walk o around w left s thrice y 
look o twice x and a look o around w left s 
run o left s after b run o around w left s 
walk o after b run o around w left s 
turn o around w right u after b look o opposite v right u twice x 
run o left s thrice y after b turn o right u thrice y 
run o twice x and a look o around w right u thrice y 
walk o around w right u thrice y after b look o around w left s 
run o opposite v right u thrice y after b walk o opposite v right u thrice y 
look o right u twice x after b run o opposite v left s 
look o opposite v right u thrice y after b look o around w right u 
walk o around w right u thrice y and a run o opposite v left s 
look o around w left s and a walk o around w right u 
walk o opposite v left s after b walk o right u twice x 
walk o around w right u thrice y and a look o right u twice x 
run o around w left s and a run o opposite v right u thrice y 
walk o left s twice x and a run o opposite v right u twice x 
look o left s thrice y and a walk o around w right u 
run o opposite v right u after b walk o around w left s 
walk o around w right u after b look o opposite v right u 
turn o opposite v left s 
walk o opposite v right u and a look o around w left s 
look o left s after b look o around w left s thrice y 
look o around w right u after b turn o right u twice x 
look o left s and a walk o around w left s twice x 
jump o 
walk o around w left s twice x and a walk o opposite v right u 
walk o right u thrice y and a walk o around w left s thrice y 
jump o 
look o opposite v left s thrice y and a walk o opposite v left s twice x 
jump o 
walk o around w right u thrice y and a walk o around w left s thrice y 
jump o 
run o left s twice x and a turn o around w right u 
jump o 
look o around w right u twice x and a look o opposite v left s twice x 
look o left s and a look o right u 
look o left s thrice y after b look o right u thrice y 
look o around w left s twice x after b run o around w left s thrice y 
jump o 
look o opposite v right u after b turn o right u twice x 
look o right u thrice y and a run o left s 
turn o opposite v left s after b run o around w left s thrice y 
look o around w right u after b run o 
walk o after b walk o right u thrice y 
walk o around w right u thrice y and a walk o 
run o around w left s and a look o opposite v left s thrice y 
run o left s thrice y and a walk o around w right u twice x 
run o opposite v right u twice x and a run o twice x 
walk o around w left s thrice y after b look o around w right u 
run o left s thrice y after b run o opposite v left s twice x 
run o thrice y and a run o around w left s 
run o opposite v left s and a run o left s 
run o opposite v right u twice x after b run o around w right u thrice y 
look o opposite v left s twice x and a look o right u thrice y 
look o around w left s thrice y after b walk o left s thrice y 
run o after b look o left s 
walk o opposite v left s twice x after b walk o opposite v right u twice x 
look o left s twice x and a walk o opposite v right u thrice y 
look o and a turn o around w left s 
turn o left s and a run o left s thrice y 
turn o around w right u and a run o opposite v right u 
look o around w left s thrice y after b look o twice x 
look o opposite v right u thrice y after b look o left s 
look o opposite v right u after b look o twice x 
look o opposite v left s thrice y after b walk o left s thrice y 
run o opposite v right u and a look o around w left s twice x 
turn o right u after b run o left s 
look o right u thrice y after b walk o around w left s twice x 
look o thrice y and a walk o right u 
run o left s thrice y after b look o opposite v left s 
look o around w right u and a run o right u 
run o right u thrice y after b look o opposite v right u twice x 
look o thrice y 
look o right u twice x and a look o right u 
turn o around w right u thrice y after b turn o left s twice x 
turn o opposite v left s twice x after b run o around w left s thrice y 
look o twice x after b walk o 
turn o left s thrice y after b turn o around w left s thrice y 
walk o right u after b look o around w right u 
run o opposite v right u twice x and a run o around w right u thrice y 
walk o around w left s after b look o right u thrice y 
turn o right u after b run o around w right u twice x 
run o right u twice x and a look o around w left s thrice y 
turn o around w left s twice x after b walk o opposite v right u twice x 
walk o around w right u after b look o right u thrice y 
run o left s after b turn o opposite v right u twice x 
turn o opposite v right u after b look o opposite v left s twice x 
walk o around w right u and a walk o right u 
jump o 
walk o opposite v right u twice x after b turn o opposite v right u thrice y 
walk o and a turn o around w right u thrice y 
walk o opposite v left s twice x after b turn o opposite v left s thrice y 
turn o opposite v right u thrice y and a turn o opposite v left s 
turn o right u thrice y after b look o right u twice x 
look o opposite v left s twice x and a turn o around w right u twice x 
turn o around w right u after b turn o left s 
turn o opposite v left s after b turn o left s twice x 
run o around w right u after b turn o right u twice x 
jump o 
run o opposite v right u thrice y and a run o around w right u twice x 
jump o 
turn o around w right u thrice y and a look o opposite v left s thrice y 
look o thrice y and a turn o opposite v left s 
look o left s twice x after b turn o left s thrice y 
jump o 
run o left s twice x after b look o left s twice x 
run o opposite v left s thrice y and a look o around w left s twice x 
look o left s and a turn o right u twice x 
run o around w left s twice x and a walk o left s thrice y 
walk o around w right u after b look o twice x 
look o opposite v right u twice x after b walk o around w left s twice x 
look o opposite v right u and a look o left s twice x 
walk o opposite v left s after b run o around w left s twice x 
turn o left s thrice y and a run o around w left s 
run o right u thrice y after b run o around w left s twice x 
jump o 
walk o opposite v left s thrice y after b look o around w left s 
look o after b walk o right u twice x 
run o around w right u after b look o around w left s thrice y 
look o right u and a walk o right u 
turn o opposite v left s thrice y after b turn o right u thrice y 
run o left s twice x and a look o opposite v right u twice x 
jump o 
run o opposite v left s twice x and a walk o 
turn o opposite v left s thrice y after b walk o left s 
turn o around w left s and a turn o opposite v left s thrice y 
walk o opposite v right u thrice y after b look o 
jump o 
look o opposite v right u and a turn o opposite v left s 
turn o right u and a turn o around w left s twice x 
walk o left s and a look o opposite v right u thrice y 
run o twice x after b walk o right u twice x 
jump o 
walk o opposite v right u and a run o right u 
turn o right u twice x and a run o opposite v right u 
jump o 
run o twice x after b walk o twice x 
run o opposite v right u twice x after b turn o right u thrice y 
run o opposite v left s twice x after b run o around w left s thrice y 
turn o right u and a look o around w left s 
run o left s twice x and a look o right u thrice y 
look o left s after b walk o left s twice x 
jump o 
walk o right u twice x and a turn o opposite v left s thrice y 
look o right u thrice y after b walk o right u 
walk o around w left s after b walk o opposite v left s 
turn o around w left s twice x after b run o thrice y 
run o around w left s twice x and a turn o opposite v right u 
run o opposite v left s after b run o left s twice x 
walk o twice x 
run o thrice y after b turn o opposite v right u twice x 
turn o opposite v left s twice x after b run o opposite v right u thrice y 
look o around w right u thrice y after b walk o right u 
jump o 
turn o right u and a look o opposite v right u thrice y 
turn o left s thrice y after b look o opposite v left s thrice y 
turn o opposite v right u and a turn o around w left s thrice y 
look o opposite v left s thrice y after b run o opposite v right u 
walk o opposite v left s thrice y after b look o left s 
walk o around w right u twice x and a run o left s twice x 
look o thrice y after b look o left s 
look o right u thrice y after b run o thrice y 
turn o opposite v left s after b turn o left s 
look o around w right u thrice y and a walk o opposite v right u thrice y 
turn o opposite v right u twice x and a walk o around w right u 
jump o 
run o right u and a run o opposite v left s thrice y 
walk o around w right u and a turn o left s twice x 
look o around w left s after b run o right u twice x 
turn o left s twice x and a look o around w left s 
walk o opposite v left s twice x and a turn o opposite v right u twice x 
turn o right u after b look o 
walk o around w right u thrice y and a walk o left s thrice y 
turn o opposite v right u and a look o around w left s 
look o left s after b look o opposite v right u 
look o opposite v right u after b look o around w right u 
run o opposite v left s thrice y and a walk o left s 
run o left s thrice y and a run o twice x 
turn o opposite v right u and a walk o around w right u twice x 
turn o right u twice x and a run o opposite v left s twice x 
turn o opposite v right u twice x and a run o twice x 
walk o around w left s thrice y after b turn o right u twice x 
look o thrice y after b run o left s twice x 
look o left s after b turn o left s 
walk o right u thrice y after b walk o right u twice x 
turn o opposite v left s and a look o left s 
look o right u thrice y and a run o around w right u thrice y 
walk o thrice y and a look o left s 
run o around w right u thrice y and a walk o opposite v left s twice x 
walk o around w left s thrice y after b run o opposite v left s 
run o and a turn o opposite v left s 
run o opposite v left s thrice y after b look o left s twice x 
turn o opposite v left s and a turn o right u 
look o opposite v left s after b turn o opposite v right u twice x 
turn o right u and a run o left s twice x 
walk o opposite v right u after b look o opposite v right u thrice y 
run o around w left s and a run o around w right u thrice y 
run o opposite v left s twice x after b turn o left s thrice y 
look o thrice y and a run o around w right u twice x 
walk o right u thrice y after b look o twice x 
walk o right u twice x after b look o opposite v left s 
jump o 
walk o left s twice x and a run o right u thrice y 
turn o opposite v right u thrice y and a turn o around w left s 
run o around w right u thrice y after b run o around w left s 
look o opposite v left s twice x and a look o twice x 
run o left s and a turn o around w left s twice x 
run o right u twice x after b look o opposite v right u twice x 
run o thrice y and a look o opposite v right u thrice y 
turn o around w right u thrice y and a walk o opposite v right u 
run o opposite v left s twice x after b turn o opposite v left s 
run o around w left s thrice y and a turn o opposite v right u twice x 
run o opposite v right u twice x and a turn o left s thrice y 
walk o right u twice x and a look o around w right u thrice y 
walk o opposite v left s and a walk o opposite v left s 
walk o opposite v right u twice x after b run o around w left s thrice y 
jump o 
turn o left s twice x after b turn o around w right u twice x 
jump o 
look o twice x and a turn o left s thrice y 
look o around w right u thrice y after b walk o around w left s 
look o opposite v left s thrice y after b turn o around w left s twice x 
jump o 
turn o left s after b run o right u 
look o around w left s thrice y and a turn o around w left s thrice y 
walk o around w right u after b look o opposite v right u twice x 
jump o 
walk o left s after b run o around w left s twice x 
turn o opposite v right u and a turn o around w right u 
look o thrice y after b walk o around w left s thrice y 
run o around w left s twice x and a look o opposite v left s thrice y 
turn o around w left s thrice y after b run o opposite v right u twice x 
look o thrice y after b run o around w right u 
walk o opposite v right u thrice y and a look o opposite v left s twice x 
walk o around w left s and a run o right u thrice y 
look o twice x after b walk o opposite v right u 
jump o 
turn o opposite v right u and a turn o left s 
walk o around w right u twice x and a run o opposite v right u 
walk o opposite v left s twice x and a run o around w left s thrice y 
look o left s twice x after b look o opposite v left s twice x 
walk o opposite v right u twice x and a look o 
walk o around w left s thrice y and a turn o opposite v left s thrice y 
look o around w left s twice x after b walk o opposite v right u thrice y 
turn o around w left s twice x and a run o left s thrice y 
look o opposite v left s twice x after b walk o right u 
turn o opposite v left s thrice y after b look o around w left s 
walk o left s twice x and a run o opposite v right u 
turn o opposite v right u twice x and a run o right u twice x 
run o around w right u after b run o around w left s thrice y 
turn o around w left s thrice y and a look o around w right u twice x 
run o right u and a look o 
look o opposite v left s thrice y and a turn o opposite v right u thrice y 
walk o left s twice x and a walk o right u 
look o opposite v left s twice x and a walk o thrice y 
walk o around w right u after b walk o opposite v left s 
walk o thrice y and a run o around w right u thrice y 
walk o around w right u twice x and a run o around w left s twice x 
run o twice x after b walk o opposite v left s thrice y 
look o opposite v left s thrice y and a walk o left s thrice y 
jump o 
jump o 
look o left s and a look o around w right u twice x 
run o right u twice x and a walk o thrice y 
run o opposite v left s thrice y after b walk o opposite v right u thrice y 
look o around w right u thrice y and a run o opposite v right u 
turn o opposite v left s twice x and a walk o twice x 
run o opposite v right u twice x after b walk o right u 
jump o 
turn o opposite v right u twice x after b turn o opposite v left s 
walk o left s twice x and a look o opposite v left s twice x 
jump o 
jump o 
turn o right u after b walk o right u 
look o right u twice x after b run o around w right u thrice y 
run o opposite v right u twice x after b look o around w left s twice x 
run o opposite v right u after b look o right u 
turn o right u twice x after b turn o around w left s twice x 
run o opposite v right u thrice y after b turn o around w left s twice x 
turn o left s twice x after b turn o around w left s thrice y 
turn o around w right u thrice y and a look o opposite v right u 
look o left s and a turn o around w right u 
turn o around w right u and a walk o right u twice x 
jump o 
turn o around w right u thrice y after b run o opposite v left s thrice y 
look o left s thrice y and a turn o opposite v left s thrice y 
run o after b walk o left s twice x 
turn o opposite v left s twice x and a look o around w right u 
look o right u twice x after b walk o around w left s 
run o around w right u after b run o around w right u twice x 
jump o 
look o around w right u twice x after b walk o around w right u 
turn o around w left s thrice y after b turn o around w right u thrice y 
jump o 
jump o 
turn o opposite v right u thrice y and a walk o around w right u thrice y 
look o left s thrice y and a turn o opposite v right u thrice y 
look o opposite v right u twice x after b look o opposite v right u 
run o twice x after b walk o opposite v right u twice x 
walk o opposite v right u thrice y after b run o opposite v right u thrice y 
turn o opposite v left s thrice y after b walk o around w right u twice x 
walk o left s thrice y after b run o thrice y 
look o opposite v right u and a look o around w left s 
walk o opposite v left s thrice y and a run o around w right u thrice y 
look o around w left s after b walk o left s thrice y 
run o opposite v right u twice x and a turn o left s 
look o and a walk o opposite v left s twice x 
walk o opposite v left s after b look o opposite v right u twice x 
look o right u twice x and a look o twice x 
walk o opposite v right u after b run o opposite v right u 
look o around w right u after b run o right u twice x 
walk o opposite v left s thrice y after b walk o around w left s twice x 
jump o 
look o right u twice x after b run o around w left s twice x 
jump o 
walk o opposite v left s after b look o around w left s 
walk o right u and a walk o opposite v left s thrice y 
walk o around w right u and a turn o around w right u 
run o around w right u after b run o 
jump o 
walk o opposite v left s after b run o right u twice x 
turn o opposite v right u thrice y and a walk o around w left s twice x 
run o opposite v right u twice x and a walk o around w right u twice x 
walk o opposite v left s and a look o opposite v left s twice x 
look o right u twice x after b look o left s thrice y 
run o right u twice x and a look o opposite v right u thrice y 
turn o opposite v right u twice x after b turn o opposite v right u twice x 
look o right u twice x and a run o left s twice x 
turn o opposite v left s after b run o opposite v right u thrice y 
turn o around w left s after b walk o right u thrice y 
turn o opposite v left s after b look o left s twice x 
turn o right u after b look o around w right u 
turn o opposite v right u and a run o 
run o twice x and a look o left s thrice y 
look o opposite v right u and a run o around w right u twice x 
run o right u thrice y after b look o left s twice x 
jump o 
run o after b run o around w right u twice x 
run o around w right u thrice y and a run o opposite v right u thrice y 
turn o left s thrice y after b walk o left s twice x 
walk o left s and a look o left s thrice y 
run o opposite v right u after b walk o opposite v left s 
run o around w right u thrice y and a run o around w right u thrice y 
walk o right u and a run o opposite v left s thrice y 
walk o around w left s twice x after b look o opposite v left s thrice y 
look o opposite v left s twice x after b run o right u twice x 
look o right u twice x and a run o around w left s 
run o opposite v right u twice x after b turn o opposite v right u twice x 
look o right u thrice y and a walk o opposite v left s thrice y 
jump o 
walk o left s twice x after b walk o left s thrice y 
look o around w right u after b walk o left s thrice y 
walk o left s thrice y after b turn o around w left s thrice y 
look o after b turn o left s twice x 
run o right u and a walk o twice x 
run o opposite v left s thrice y after b run o around w left s twice x 
walk o opposite v left s thrice y and a walk o right u thrice y 
run o left s twice x and a run o opposite v right u twice x 
run o thrice y and a look o left s twice x 
walk o opposite v right u after b run o opposite v left s twice x 
walk o around w right u thrice y and a turn o around w right u 
turn o left s twice x after b look o twice x 
turn o left s thrice y after b run o around w right u twice x 
turn o opposite v right u twice x and a look o right u twice x 
run o thrice y and a run o right u 
run o opposite v left s after b walk o right u 
walk o opposite v left s twice x after b turn o left s thrice y 
look o thrice y and a walk o opposite v right u 
look o around w right u twice x and a walk o around w left s thrice y 
run o around w right u and a turn o opposite v left s thrice y 
run o left s after b run o 
look o around w left s and a walk o left s 
walk o around w left s thrice y and a run o opposite v right u thrice y 
walk o around w right u twice x after b run o around w right u thrice y 
turn o around w right u thrice y and a look o left s 
run o right u thrice y and a turn o opposite v left s thrice y 
walk o right u and a walk o opposite v right u twice x 
run o left s after b walk o left s 
look o around w right u and a look o right u thrice y 
turn o opposite v right u twice x after b turn o opposite v left s twice x 
walk o left s twice x after b run o around w right u thrice y 
run o left s twice x after b look o around w right u twice x 
turn o left s twice x after b walk o opposite v right u thrice y 
jump o 
run o around w left s after b run o left s 
look o twice x and a look o left s thrice y 
walk o and a look o opposite v right u twice x 
look o left s twice x and a look o opposite v left s 
turn o around w left s thrice y and a run o right u twice x 
look o around w right u and a walk o opposite v right u twice x 
look o around w left s after b look o opposite v right u thrice y 
turn o around w left s twice x and a look o opposite v right u 
run o opposite v left s and a run o 
look o opposite v right u after b run o around w right u 
look o around w left s thrice y and a walk o opposite v left s 
jump o 
jump o 
look o thrice y and a turn o around w right u twice x 
run o around w left s thrice y and a run o around w right u twice x 
look o around w right u twice x after b turn o around w right u twice x 
turn o right u after b look o left s thrice y 
turn o left s thrice y and a turn o around w right u 
look o opposite v right u after b run o left s twice x 
run o opposite v left s thrice y and a run o left s 
turn o around w left s and a look o left s twice x 
look o right u and a turn o left s twice x 
look o left s after b walk o around w left s thrice y 
run o around w left s twice x and a run o opposite v left s thrice y 
run o around w left s thrice y after b walk o opposite v right u thrice y 
run o around w left s and a walk o left s thrice y 
jump o 
run o around w left s twice x and a turn o right u thrice y 
walk o around w left s twice x after b turn o around w right u 
walk o right u after b turn o opposite v right u twice x 
look o opposite v right u after b walk o right u thrice y 
look o left s thrice y and a turn o around w right u thrice y 
look o opposite v right u thrice y and a run o left s thrice y 
run o right u and a turn o around w right u thrice y 
turn o right u after b turn o opposite v right u 
look o around w right u and a turn o opposite v left s 
run o after b walk o opposite v left s 
jump o 
look o thrice y after b walk o around w right u twice x 
walk o around w right u twice x after b walk o opposite v left s 
turn o right u thrice y and a run o left s twice x 
look o around w left s thrice y after b walk o opposite v right u 
turn o left s twice x after b run o left s twice x 
look o opposite v left s twice x after b look o right u twice x 
look o around w left s and a run o thrice y 
run o opposite v right u after b walk o 
jump o 
look o opposite v left s and a run o left s twice x 
look o around w right u thrice y after b walk o opposite v left s twice x 
run o after b run o twice x 
turn o around w right u thrice y after b walk o right u thrice y 
look o around w left s twice x and a look o opposite v left s thrice y 
look o around w right u and a run o around w right u 
look o around w right u and a walk o around w left s 
run o opposite v right u after b run o around w left s thrice y 
run o left s after b turn o around w right u twice x 
run o left s thrice y and a look o around w right u twice x 
turn o around w right u and a run o around w left s thrice y 
look o right u after b walk o 
run o around w left s thrice y after b run o around w right u 
walk o opposite v right u and a turn o around w left s twice x 
look o around w right u thrice y after b walk o opposite v right u thrice y 
run o left s twice x and a run o opposite v right u 
turn o opposite v left s and a look o opposite v right u thrice y 
look o right u thrice y after b walk o around w left s thrice y 
jump o 
run o right u and a look o opposite v right u twice x 
walk o opposite v left s after b turn o left s thrice y 
run o around w right u after b turn o opposite v right u twice x 
walk o around w left s thrice y after b run o around w left s twice x 
look o right u twice x and a run o left s thrice y 
run o opposite v right u thrice y after b walk o left s thrice y 
jump o 
run o around w right u and a look o opposite v right u 
turn o opposite v left s after b run o 
look o left s twice x and a look o around w right u 
walk o right u and a look o left s thrice y 
walk o thrice y and a walk o around w right u thrice y 
turn o around w left s twice x after b walk o opposite v left s 
run o opposite v left s twice x after b walk o thrice y 
walk o around w left s and a look o around w left s thrice y 
run o left s after b look o opposite v left s 
run o opposite v left s thrice y 
turn o around w right u twice x and a look o opposite v right u thrice y 
walk o opposite v left s twice x and a turn o opposite v left s twice x 
look o opposite v right u thrice y and a look o left s 
walk o opposite v left s twice x after b walk o opposite v right u thrice y 
walk o around w left s after b turn o opposite v right u twice x 
turn o right u thrice y after b run o 
walk o opposite v left s thrice y and a look o around w left s twice x 
run o around w left s thrice y after b run o 
look o thrice y after b run o right u 
turn o opposite v left s thrice y after b look o around w left s thrice y 
walk o right u twice x and a walk o 
look o opposite v left s twice x after b turn o left s 
turn o right u twice x and a turn o opposite v left s thrice y 
turn o left s and a run o left s twice x 
run o opposite v left s twice x and a walk o thrice y 
run o around w left s and a walk o right u twice x 
look o right u after b walk o right u thrice y 
run o right u twice x after b walk o around w left s 
run o left s thrice y and a look o thrice y 
walk o twice x and a run o left s twice x 
jump o 
walk o left s thrice y after b turn o opposite v right u thrice y 
walk o around w left s and a run o right u twice x 
walk o around w left s thrice y after b turn o opposite v right u thrice y 
look o after b turn o around w right u twice x 
jump o 
walk o right u twice x and a run o around w right u thrice y 
run o opposite v left s after b look o around w right u 
jump o 
walk o right u thrice y and a look o opposite v right u thrice y 
turn o right u and a walk o opposite v right u twice x 
look o right u twice x and a turn o opposite v left s thrice y 
turn o left s twice x after b run o opposite v left s thrice y 
walk o around w left s thrice y and a turn o left s 
walk o right u twice x and a turn o around w right u twice x 
walk o and a look o around w right u thrice y 
run o opposite v left s thrice y and a look o left s twice x 
walk o twice x after b look o around w left s twice x 
walk o around w left s thrice y and a turn o around w left s 
look o around w right u and a turn o opposite v right u 
run o opposite v left s thrice y and a look o opposite v left s thrice y 
walk o opposite v right u and a run o opposite v left s 
run o around w right u thrice y and a run o 
jump o 
walk o opposite v left s and a walk o around w right u 
turn o around w right u thrice y and a turn o opposite v right u 
turn o opposite v right u twice x after b turn o left s 
run o opposite v right u thrice y and a look o opposite v left s thrice y 
jump o 
turn o right u thrice y after b look o around w left s twice x 
look o thrice y and a walk o left s 
walk o right u twice x and a run o left s thrice y 
look o opposite v left s twice x and a turn o left s 
run o left s thrice y after b look o right u thrice y 
run o around w left s thrice y and a walk o right u thrice y 
turn o left s after b run o around w right u twice x 
walk o opposite v left s twice x after b look o opposite v left s thrice y 
run o left s twice x after b look o opposite v right u twice x 
run o opposite v left s after b look o left s thrice y 
walk o opposite v right u twice x after b run o right u 
walk o opposite v right u and a look o opposite v left s thrice y 
run o around w right u thrice y after b run o thrice y 
walk o around w right u twice x after b run o left s 
look o opposite v left s after b look o opposite v left s twice x 
run o around w right u and a walk o opposite v left s thrice y 
look o around w right u thrice y and a run o around w left s thrice y 
jump o 
run o twice x after b look o thrice y 
run o around w right u after b look o left s thrice y 
turn o right u twice x and a look o opposite v right u thrice y 
walk o around w right u twice x and a turn o left s 
look o left s and a turn o right u thrice y 
look o around w right u after b walk o around w left s thrice y 
run o around w right u twice x after b turn o left s 
walk o around w right u and a look o left s thrice y 
walk o opposite v left s twice x after b look o around w left s thrice y 
look o thrice y after b walk o opposite v right u thrice y 
turn o opposite v right u thrice y after b run o opposite v right u twice x 
look o opposite v right u thrice y after b turn o opposite v left s 
jump o 
walk o right u and a look o around w right u twice x 
run o opposite v left s after b run o around w right u 
run o left s after b walk o around w left s 
run o around w left s thrice y after b look o opposite v left s 
jump o 
look o opposite v left s twice x and a walk o right u 
turn o around w left s twice x after b look o opposite v right u thrice y 
walk o around w left s after b look o twice x 
walk o right u thrice y after b look o around w left s twice x 
run o around w right u thrice y after b run o opposite v left s thrice y 
walk o left s and a look o right u thrice y 
look o right u and a walk o around w right u thrice y 
look o after b turn o opposite v right u thrice y 
turn o left s thrice y 
look o opposite v right u thrice y and a walk o right u thrice y 
jump o 
look o left s thrice y and a turn o left s thrice y 
run o opposite v right u and a walk o right u twice x 
jump o 
turn o around w left s twice x and a turn o right u thrice y 
look o opposite v left s and a turn o around w left s twice x 
turn o opposite v right u after b run o right u twice x 
run o twice x and a run o opposite v right u 
run o around w right u and a turn o opposite v left s twice x 
turn o around w left s after b look o opposite v left s twice x 
run o right u and a look o around w left s 
run o and a walk o opposite v right u thrice y 
run o opposite v right u thrice y after b run o around w left s twice x 
turn o opposite v right u and a run o opposite v right u twice x 
walk o right u thrice y and a look o around w left s thrice y 
look o around w left s thrice y after b turn o around w right u twice x 
run o twice x after b run o right u thrice y 
run o around w left s after b walk o around w right u 
look o around w left s thrice y and a turn o right u twice x 
walk o right u thrice y and a walk o opposite v left s 
turn o around w left s thrice y and a look o around w left s 
run o around w left s twice x and a turn o around w left s thrice y 
jump o 
walk o around w right u thrice y after b look o right u 
run o opposite v left s thrice y after b look o around w right u 
run o opposite v right u thrice y and a walk o right u twice x 
walk o opposite v right u thrice y after b look o around w left s 
walk o right u twice x after b run o around w right u thrice y 
turn o opposite v right u twice x after b turn o opposite v left s thrice y 
jump o 
run o left s after b look o opposite v left s thrice y 
walk o and a look o left s thrice y 
turn o opposite v right u twice x after b turn o around w left s 
turn o left s thrice y after b look o thrice y 
look o left s after b run o opposite v left s twice x 
walk o left s thrice y and a walk o opposite v right u thrice y 
turn o around w left s after b walk o right u twice x 
look o opposite v right u twice x and a run o right u thrice y 
turn o around w left s and a look o right u 
walk o around w left s after b run o left s thrice y 
turn o left s twice x after b turn o opposite v right u 
run o thrice y after b walk o left s twice x 
turn o around w left s thrice y and a look o twice x 
walk o around w right u after b walk o left s 
run o thrice y after b run o 
look o around w right u thrice y after b walk o left s thrice y 
walk o left s and a walk o around w right u 
run o right u twice x after b turn o around w left s 
look o right u twice x and a run o around w right u 
look o around w left s after b look o opposite v right u 
run o around w left s twice x and a look o opposite v left s twice x 
look o around w right u twice x and a turn o opposite v right u 
run o opposite v right u thrice y and a run o around w left s thrice y 
jump o 
walk o twice x and a walk o right u twice x 
look o opposite v right u thrice y and a turn o around w left s twice x 
jump o 
walk o opposite v right u twice x and a turn o left s 
run o around w right u after b walk o around w left s twice x 
run o left s and a turn o opposite v left s twice x 
run o twice x and a walk o opposite v right u 
turn o right u twice x and a turn o left s twice x 
look o right u and a look o twice x 
look o around w right u thrice y after b look o opposite v right u twice x 
walk o after b look o twice x 
walk o left s after b walk o around w right u twice x 
walk o and a run o around w left s thrice y 
walk o opposite v left s after b run o opposite v left s twice x 
jump o 
jump o 
run o thrice y and a run o opposite v right u twice x 
look o left s thrice y after b walk o around w right u 
look o opposite v left s after b look o 
run o around w left s and a run o 
run o around w right u after b turn o left s thrice y 
turn o around w right u thrice y after b look o right u thrice y 
look o around w right u thrice y after b turn o left s 
run o opposite v left s thrice y and a run o right u twice x 
walk o opposite v left s thrice y after b run o opposite v left s thrice y 
run o left s thrice y after b walk o opposite v right u 
run o right u thrice y and a walk o opposite v left s thrice y 
jump o 
walk o opposite v right u twice x and a walk o twice x 
walk o left s thrice y and a look o around w left s thrice y 
look o opposite v right u twice x after b look o around w right u 
walk o left s and a look o opposite v right u 
turn o left s thrice y after b walk o opposite v left s 
run o left s after b turn o around w left s 
run o opposite v left s thrice y after b run o around w right u thrice y 
run o opposite v right u thrice y and a look o left s twice x 
run o left s thrice y and a run o opposite v right u 
run o right u thrice y and a run o right u 
look o opposite v left s after b walk o opposite v left s thrice y 
run o around w left s thrice y and a look o right u thrice y 
turn o left s twice x and a turn o around w right u twice x 
turn o around w right u twice x after b run o around w left s 
run o around w right u twice x and a turn o opposite v right u thrice y 
look o opposite v right u and a run o right u twice x 
turn o opposite v left s and a walk o around w left s twice x 
walk o thrice y after b look o opposite v right u thrice y 
run o twice x after b run o right u twice x 
look o opposite v right u twice x after b turn o left s twice x 
turn o left s twice x after b walk o opposite v left s thrice y 
walk o around w right u and a walk o opposite v right u thrice y 
run o thrice y and a walk o around w right u twice x 
jump o 
walk o around w left s thrice y and a walk o opposite v right u thrice y 
look o right u thrice y after b run o around w left s thrice y 
run o around w right u thrice y and a look o around w left s 
run o around w right u after b turn o around w left s thrice y 
turn o opposite v right u after b look o 
run o opposite v right u and a look o left s twice x 
run o twice x after b turn o opposite v right u twice x 
run o right u thrice y and a walk o left s twice x 
look o around w right u thrice y and a look o opposite v left s 
look o right u and a look o around w left s thrice y 
turn o around w right u twice x and a run o twice x 
walk o around w right u thrice y and a walk o around w right u thrice y 
run o opposite v left s thrice y and a look o right u twice x 
turn o opposite v left s twice x after b walk o around w left s twice x 
walk o twice x and a walk o around w right u twice x 
run o right u after b run o left s thrice y 
jump o 
walk o opposite v right u twice x and a run o opposite v right u thrice y 
turn o around w left s twice x and a turn o opposite v left s thrice y 
look o opposite v right u thrice y and a look o around w left s 
run o around w right u after b look o opposite v right u twice x 
look o around w right u and a run o opposite v left s thrice y 
look o left s and a turn o opposite v right u thrice y 
walk o opposite v left s thrice y after b walk o around w left s thrice y 
turn o opposite v left s twice x after b run o around w right u 
walk o around w left s twice x and a look o 
turn o right u thrice y and a walk o around w right u thrice y 
turn o right u twice x and a run o right u thrice y 
run o around w left s after b run o right u twice x 
walk o left s and a look o right u twice x 
walk o around w right u thrice y after b walk o right u 
run o left s twice x and a walk o left s thrice y 
walk o opposite v left s after b look o right u 
walk o left s twice x after b run o opposite v right u thrice y 
turn o left s twice x after b walk o around w right u 
turn o right u and a walk o left s thrice y 
turn o around w left s thrice y and a look o left s thrice y 
run o opposite v right u twice x and a look o 
run o opposite v right u after b walk o opposite v right u twice x 
look o left s and a look o left s twice x 
look o opposite v left s twice x after b turn o right u thrice y 
turn o around w right u and a walk o twice x 
walk o right u twice x and a run o left s 
walk o opposite v left s twice x and a look o around w left s twice x 
run o opposite v right u thrice y and a turn o opposite v right u thrice y 
look o left s after b run o opposite v left s thrice y 
look o right u and a walk o around w left s 
turn o around w left s and a walk o left s twice x 
run o opposite v left s after b walk o left s twice x 
run o after b look o thrice y 
look o twice x after b walk o opposite v right u twice x 
walk o opposite v right u twice x after b turn o opposite v left s twice x 
look o around w right u after b turn o right u 
turn o opposite v right u and a turn o left s twice x 
walk o left s after b run o opposite v right u twice x 
look o left s twice x and a turn o right u 
turn o around w left s twice x after b look o twice x 
run o right u and a look o right u 
jump o 
turn o opposite v right u and a turn o right u thrice y 
jump o 
run o opposite v right u twice x after b run o opposite v right u thrice y 
look o left s after b look o left s thrice y 
look o around w right u and a run o opposite v left s 
run o left s thrice y after b walk o around w right u twice x 
run o opposite v left s thrice y and a walk o around w left s thrice y 
run o left s thrice y and a turn o around w left s 
look o opposite v right u thrice y and a look o opposite v right u 
run o twice x after b look o around w right u twice x 
look o around w right u twice x after b look o opposite v right u thrice y 
walk o around w right u and a turn o around w left s 
run o around w right u twice x and a walk o left s thrice y 
turn o left s twice x and a run o opposite v left s thrice y 
walk o around w left s thrice y 
turn o left s after b turn o around w left s 
look o left s thrice y and a look o around w right u 
walk o around w left s thrice y after b look o right u thrice y 
run o opposite v left s after b look o around w right u twice x 
jump o 
look o right u thrice y after b turn o right u 
turn o around w right u after b walk o around w right u 
run o around w left s and a look o twice x 
jump o 
look o opposite v left s twice x and a run o right u 
run o opposite v right u thrice y and a walk o opposite v left s 
jump o 
run o opposite v right u twice x after b turn o opposite v left s twice x 
turn o left s twice x after b look o opposite v right u thrice y 
look o opposite v left s thrice y after b walk o right u thrice y 
look o left s and a look o opposite v left s twice x 
walk o around w right u twice x after b look o 
walk o opposite v left s after b turn o right u 
turn o around w right u thrice y after b look o around w right u twice x 
run o around w right u thrice y after b walk o around w left s twice x 
look o opposite v right u after b run o around w right u thrice y 
run o left s and a walk o thrice y 
walk o after b look o around w right u twice x 
turn o around w right u thrice y after b walk o right u twice x 
run o left s and a run o twice x 
run o opposite v left s twice x after b walk o opposite v left s thrice y 
run o right u thrice y and a look o around w left s thrice y 
walk o right u thrice y after b run o around w right u thrice y 
turn o around w left s thrice y after b look o right u thrice y 
run o left s twice x and a look o around w right u twice x 
run o around w right u thrice y and a run o opposite v right u 
walk o right u after b turn o opposite v left s 
run o and a look o around w left s 
turn o opposite v right u thrice y after b turn o opposite v right u thrice y 
look o around w right u thrice y after b walk o left s 
turn o right u twice x and a turn o opposite v right u 
look o left s after b look o around w left s 
jump o 
look o left s thrice y after b look o opposite v left s thrice y 
walk o right u after b turn o around w left s thrice y 
run o right u twice x after b turn o around w right u twice x 
jump o 
look o and a run o right u thrice y 
run o thrice y after b look o left s thrice y 
walk o around w left s thrice y and a turn o opposite v right u 
walk o around w left s twice x and a turn o right u thrice y 
look o opposite v left s and a turn o around w left s 
look o left s twice x after b run o opposite v left s twice x 
look o opposite v left s and a run o twice x 
walk o twice x after b turn o opposite v right u twice x 
run o opposite v right u twice x after b turn o opposite v right u 
look o opposite v left s twice x and a look o around w left s 
run o opposite v left s thrice y and a run o around w right u 
turn o around w right u thrice y and a look o opposite v left s 
run o left s twice x after b walk o opposite v left s 
run o opposite v left s twice x after b run o right u 
walk o around w left s thrice y and a look o opposite v left s twice x 
jump o 
run o left s after b turn o left s thrice y 
walk o opposite v right u and a walk o opposite v left s twice x 
look o right u thrice y and a look o around w left s thrice y 
look o left s and a turn o right u 
turn o around w right u twice x after b run o right u thrice y 
run o opposite v left s after b walk o around w left s twice x 
jump o 
run o opposite v left s and a walk o opposite v left s 
run o around w right u and a look o right u thrice y 
walk o left s and a run o opposite v left s thrice y 
turn o opposite v right u twice x after b walk o around w right u 
walk o twice x and a walk o opposite v left s thrice y 
look o around w left s twice x and a turn o opposite v right u 
look o and a look o left s twice x 
turn o opposite v left s twice x after b look o right u 
turn o around w left s twice x after b walk o around w left s 
turn o left s twice x and a walk o around w right u 
jump o 
look o opposite v left s thrice y and a walk o twice x 
walk o after b turn o opposite v right u twice x 
turn o right u and a walk o around w left s 
run o opposite v left s after b look o around w right u thrice y 
turn o around w right u twice x and a turn o opposite v left s twice x 
look o right u thrice y and a look o around w right u 
look o around w right u and a look o around w right u thrice y 
look o opposite v right u thrice y and a turn o opposite v right u twice x 
run o opposite v right u thrice y and a turn o right u twice x 
turn o left s twice x and a turn o right u thrice y 
turn o around w right u and a look o opposite v right u twice x 
run o opposite v left s thrice y and a run o around w right u twice x 
run o around w left s after b look o opposite v left s thrice y 
walk o around w left s thrice y after b walk o left s twice x 
walk o right u thrice y after b look o around w right u thrice y 
look o opposite v left s and a walk o opposite v right u twice x 
run o twice x and a walk o right u twice x 
turn o opposite v right u thrice y and a run o around w left s twice x 
run o after b turn o left s twice x 
walk o around w right u thrice y after b look o opposite v right u 
turn o right u thrice y after b turn o opposite v right u thrice y 
turn o opposite v right u twice x after b run o 
run o around w right u and a run o left s 
walk o right u twice x after b turn o around w right u 
look o opposite v left s thrice y after b run o left s thrice y 
look o left s thrice y after b run o around w left s twice x 
walk o around w left s thrice y after b look o right u twice x 
run o opposite v right u thrice y and a walk o twice x 
run o right u twice x after b look o left s thrice y 
run o around w right u twice x and a run o right u 
run o twice x and a turn o opposite v left s thrice y 
turn o right u twice x after b look o opposite v right u twice x 
walk o left s twice x after b run o around w right u twice x 
turn o opposite v left s twice x and a walk o right u twice x 
run o around w left s twice x after b turn o right u 
turn o around w left s twice x and a turn o left s 
jump o 
look o around w left s thrice y and a look o left s 
run o twice x and a walk o around w right u thrice y 
look o around w right u and a turn o right u thrice y 
walk o right u after b turn o right u thrice y 
walk o right u twice x after b look o left s 
look o around w right u twice x after b turn o opposite v left s twice x 
walk o left s after b walk o around w left s 
walk o opposite v right u thrice y and a turn o opposite v right u 
walk o around w left s thrice y and a walk o opposite v left s thrice y 
run o and a walk o around w left s 
run o around w left s after b walk o opposite v left s twice x 
turn o opposite v left s after b walk o opposite v left s 
turn o right u twice x and a look o thrice y 
run o around w left s thrice y after b run o around w left s thrice y 
look o around w left s twice x and a walk o left s 
run o left s thrice y and a run o around w left s thrice y 
turn o opposite v right u twice x after b run o around w right u twice x 
turn o around w left s and a look o thrice y 
look o opposite v right u twice x and a turn o right u 
run o right u thrice y and a walk o left s 
walk o twice x and a walk o twice x 
turn o around w right u twice x and a walk o opposite v left s 
look o opposite v left s twice x and a run o opposite v left s thrice y 
run o left s thrice y and a walk o twice x 
run o around w left s thrice y after b run o around w right u thrice y 
run o opposite v left s thrice y after b walk o right u twice x 
walk o around w left s twice x and a look o around w left s twice x 
run o left s twice x after b turn o around w right u 
run o thrice y and a look o right u thrice y 
run o around w right u after b run o opposite v left s thrice y 
turn o around w left s thrice y after b run o twice x 
run o left s thrice y and a run o right u twice x 
run o opposite v left s twice x and a look o around w left s thrice y 
look o right u thrice y after b run o opposite v right u twice x 
look o opposite v right u after b look o left s twice x 
walk o opposite v left s thrice y and a walk o around w left s thrice y 
turn o right u twice x after b walk o 
look o twice x and a walk o thrice y 
walk o right u twice x after b turn o around w left s twice x 
jump o 
jump o 
walk o around w left s twice x and a run o around w right u thrice y 
turn o opposite v left s thrice y after b walk o right u thrice y 
run o and a turn o around w right u 
walk o left s thrice y and a walk o opposite v right u twice x 
turn o around w left s thrice y and a run o opposite v left s twice x 
turn o opposite v right u and a walk o around w left s twice x 
jump o 
turn o around w left s twice x and a turn o left s thrice y 
turn o left s and a look o opposite v right u thrice y 
turn o left s twice x after b run o opposite v right u 
walk o after b look o around w left s twice x 
turn o left s after b walk o around w left s 
walk o around w left s thrice y after b walk o opposite v right u twice x 
walk o around w left s thrice y after b walk o around w right u thrice y 
run o opposite v right u twice x after b walk o around w right u twice x 
look o around w left s after b walk o around w right u thrice y 
turn o opposite v right u thrice y after b turn o opposite v left s twice x 
walk o left s thrice y and a walk o right u thrice y 
look o around w right u thrice y and a look o right u thrice y 
turn o around w right u thrice y and a run o left s thrice y 
turn o opposite v left s thrice y after b run o around w right u 
jump o 
turn o left s twice x and a look o opposite v left s 
turn o left s twice x and a run o opposite v right u twice x 
look o around w left s twice x after b run o twice x 
turn o around w right u thrice y and a run o around w left s twice x 
look o opposite v left s thrice y and a turn o around w left s 
run o around w right u and a run o left s thrice y 
look o around w right u thrice y after b run o right u 
look o around w left s twice x after b walk o 
walk o around w right u after b walk o opposite v right u thrice y 
turn o right u twice x and a run o around w left s 
run o opposite v left s thrice y and a run o around w left s twice x 
look o opposite v right u twice x after b turn o around w left s twice x 
walk o right u thrice y after b turn o opposite v left s twice x 
walk o opposite v right u thrice y and a walk o opposite v left s twice x 
look o around w left s thrice y after b look o opposite v right u thrice y 
walk o around w left s and a look o right u 
turn o around w right u after b run o 
walk o around w left s twice x and a run o left s 
walk o left s twice x and a turn o around w left s 
look o around w left s and a walk o opposite v left s twice x 
jump o 
run o left s twice x and a turn o right u twice x 
turn o around w right u after b walk o around w right u thrice y 
run o around w right u thrice y and a turn o opposite v right u 
look o thrice y and a run o opposite v right u twice x 
run o opposite v right u thrice y and a walk o around w left s thrice y 
jump o 
run o around w left s and a look o thrice y 
run o left s and a walk o around w left s twice x 
look o opposite v left s thrice y and a walk o around w left s thrice y 
turn o opposite v left s thrice y and a walk o around w right u 
walk o opposite v left s twice x after b run o left s thrice y 
run o right u twice x and a look o right u twice x 
walk o opposite v left s thrice y after b turn o right u 
look o opposite v right u thrice y and a run o right u twice x 
walk o around w left s twice x after b turn o opposite v left s thrice y 
look o opposite v right u twice x and a look o opposite v left s twice x 
jump o 
look o left s twice x after b walk o around w right u 
run o opposite v right u twice x and a look o left s twice x 
jump o 
jump o 
walk o left s twice x after b turn o around w right u twice x 
walk o opposite v right u twice x and a look o opposite v left s twice x 
turn o around w left s twice x after b walk o opposite v right u thrice y 
jump o 
jump o 
walk o right u and a walk o 
walk o around w right u thrice y and a look o around w left s thrice y 
turn o opposite v right u after b turn o around w left s 
walk o right u and a walk o opposite v left s twice x 
walk o around w right u after b run o 
run o right u after b look o opposite v right u 
run o opposite v right u after b turn o opposite v right u twice x 
run o left s thrice y after b run o opposite v right u thrice y 
turn o around w left s thrice y after b turn o around w left s thrice y 
turn o right u thrice y and a look o opposite v right u 
run o left s twice x and a turn o around w left s twice x 
walk o around w right u twice x after b look o opposite v right u twice x 
run o opposite v left s twice x after b run o around w left s twice x 
walk o around w right u thrice y after b walk o 
run o around w left s after b look o around w left s 
look o opposite v right u thrice y after b run o opposite v right u thrice y 
turn o opposite v right u and a turn o around w right u thrice y 
turn o left s twice x and a look o right u thrice y 
walk o thrice y after b turn o around w right u 
turn o opposite v left s twice x after b walk o around w left s 
run o opposite v left s thrice y after b walk o right u thrice y 
look o right u after b look o twice x 
run o opposite v left s thrice y and a walk o left s twice x 
run o around w left s thrice y after b turn o opposite v right u twice x 
turn o right u after b look o opposite v left s thrice y 
turn o around w right u twice x and a turn o around w left s twice x 
turn o right u and a turn o left s twice x 
jump o 
walk o right u thrice y after b look o left s thrice y 
run o around w left s twice x after b walk o around w left s thrice y 
run o around w left s twice x after b walk o right u 
jump o 
walk o around w right u thrice y after b run o around w right u thrice y 
look o left s after b run o around w left s twice x 
run o around w left s thrice y after b walk o left s twice x 
look o around w right u thrice y after b turn o around w right u thrice y 
walk o opposite v right u after b walk o around w left s 
run o around w left s twice x and a turn o right u 
look o right u twice x after b look o opposite v left s 
run o left s and a look o thrice y 
jump o 
run o left s thrice y and a run o right u thrice y 
jump o 
look o left s twice x after b walk o thrice y 
run o around w left s twice x and a walk o right u 
walk o left s twice x and a walk o around w right u thrice y 
turn o right u and a turn o around w left s thrice y 
walk o thrice y after b look o around w left s 
run o around w left s twice x and a turn o around w right u thrice y 
walk o around w right u thrice y after b turn o around w right u 
walk o left s and a run o right u thrice y 
turn o around w left s thrice y and a walk o around w right u thrice y 
turn o left s twice x after b look o left s 
walk o around w right u twice x and a walk o left s thrice y 
walk o and a turn o around w left s 
run o opposite v left s thrice y after b run o thrice y 
run o opposite v left s twice x and a walk o twice x 
walk o around w left s twice x after b run o around w left s 
run o around w right u and a walk o 
walk o around w right u twice x and a run o right u twice x 
run o around w right u twice x after b look o around w right u thrice y 
run o opposite v right u thrice y after b turn o around w right u thrice y 
run o around w right u twice x and a walk o around w left s twice x 
run o opposite v left s thrice y and a turn o around w left s twice x 
look o around w right u thrice y and a turn o around w right u 
turn o around w left s thrice y and a turn o opposite v left s twice x 
run o left s after b look o opposite v right u twice x 
run o right u thrice y after b walk o right u twice x 
turn o around w left s twice x and a turn o opposite v right u 
jump o 
turn o around w left s after b walk o around w right u thrice y 
walk o right u thrice y after b walk o right u 
turn o right u and a look o thrice y 
turn o opposite v left s after b run o opposite v left s twice x 
walk o left s thrice y and a run o opposite v right u thrice y 
walk o opposite v left s thrice y after b run o opposite v right u thrice y 
turn o around w left s after b run o left s twice x 
run o left s and a turn o left s 
walk o right u thrice y and a turn o left s twice x 
walk o opposite v right u thrice y after b turn o around w left s thrice y 
run o thrice y after b turn o left s 
walk o opposite v left s twice x after b look o right u thrice y 
jump o 
look o around w right u twice x and a walk o opposite v left s 
run o opposite v right u twice x after b look o around w right u 
run o around w left s twice x after b walk o opposite v right u 
jump o 
walk o right u and a turn o right u 
turn o left s thrice y and a look o around w right u thrice y 
run o opposite v left s after b look o around w left s twice x 
run o thrice y and a run o left s 
run o left s thrice y after b walk o opposite v right u thrice y 
look o left s twice x after b walk o around w right u thrice y 
jump o 
run o around w right u twice x after b walk o thrice y 
run o right u twice x after b walk o opposite v left s twice x 
look o around w left s and a look o around w left s twice x 
run o twice x and a run o 
jump o 
run o left s twice x and a look o around w left s thrice y 
look o around w right u twice x and a run o around w left s 
walk o around w left s and a run o opposite v left s 
turn o opposite v left s twice x after b run o left s twice x 
look o left s twice x after b look o around w right u thrice y 
look o left s thrice y and a turn o left s twice x 
walk o around w right u twice x and a look o thrice y 
look o left s thrice y and a run o right u thrice y 
turn o opposite v left s and a walk o around w left s 
run o around w left s thrice y after b look o thrice y 
walk o around w left s twice x 
look o right u twice x and a look o around w right u 
look o left s twice x after b run o around w left s thrice y 
turn o opposite v left s and a turn o opposite v left s twice x 
walk o around w left s twice x and a walk o opposite v right u thrice y 
jump o 
run o opposite v right u and a run o opposite v right u 
run o around w left s twice x and a run o left s thrice y 
walk o around w left s thrice y and a turn o around w right u twice x 
run o left s thrice y after b look o around w right u twice x 
run o twice x after b run o right u 
run o around w right u twice x and a run o opposite v left s 
run o thrice y after b turn o opposite v left s thrice y 
run o opposite v right u thrice y and a turn o around w right u thrice y 
run o right u after b run o around w right u twice x 
jump o 
turn o right u thrice y after b look o opposite v left s twice x 
run o around w right u thrice y after b walk o left s 
look o around w left s thrice y after b look o right u thrice y 
walk o opposite v left s after b walk o right u 
jump o 
look o thrice y and a run o opposite v left s thrice y 
look o around w right u twice x after b walk o around w left s 
run o around w right u and a look o around w left s 
walk o opposite v right u twice x after b walk o 
turn o right u and a look o opposite v right u 
look o around w right u thrice y after b look o thrice y 
run o opposite v right u twice x and a look o left s 
walk o left s and a look o around w left s twice x 
run o left s twice x after b look o opposite v right u thrice y 
look o opposite v left s twice x after b run o left s thrice y 
look o and a look o opposite v right u thrice y 
look o opposite v right u thrice y and a walk o twice x 
run o twice x and a run o right u twice x 
jump o 
look o right u and a run o right u twice x 
turn o around w left s and a turn o right u 
turn o right u after b turn o around w left s thrice y 
run o around w left s after b walk o opposite v left s thrice y 
look o thrice y after b turn o around w left s twice x 
walk o left s after b walk o right u 
walk o around w left s and a walk o opposite v right u thrice y 
run o opposite v left s and a look o twice x 
walk o opposite v right u and a run o left s thrice y 
walk o left s twice x after b look o around w right u thrice y 
look o opposite v right u and a run o opposite v left s 
jump o 
turn o opposite v left s and a walk o opposite v right u 
turn o right u after b run o opposite v right u thrice y 
look o left s thrice y and a run o around w right u twice x 
jump o 
jump o 
walk o around w left s twice x after b look o around w right u twice x 
walk o right u after b turn o right u 
run o right u twice x and a walk o 
walk o right u and a turn o opposite v left s 
walk o opposite v right u thrice y and a run o opposite v right u 
look o opposite v right u thrice y after b run o opposite v left s thrice y 
turn o right u after b turn o left s twice x 
run o opposite v right u after b turn o opposite v right u 
walk o left s twice x and a look o opposite v left s thrice y 
turn o right u twice x 
run o right u twice x after b walk o right u thrice y 
turn o around w left s and a look o twice x 
look o opposite v right u thrice y and a walk o opposite v right u 
look o left s thrice y after b run o around w right u thrice y 
look o around w right u twice x after b turn o around w left s thrice y 
turn o around w left s twice x after b walk o around w right u twice x 
turn o around w right u and a walk o around w right u twice x 
look o around w right u and a turn o right u twice x 
turn o opposite v right u after b look o opposite v right u thrice y 
look o around w left s after b walk o around w right u twice x 
look o after b walk o opposite v right u thrice y 
run o opposite v right u twice x after b run o around w left s 
look o right u thrice y and a walk o right u 
turn o around w left s after b walk o around w left s thrice y 
jump o 
jump o 
turn o left s thrice y after b turn o around w right u 
run o opposite v left s thrice y and a walk o right u thrice y 
look o opposite v right u twice x and a walk o left s thrice y 
look o around w right u twice x after b walk o around w left s twice x 
turn o opposite v left s and a turn o around w right u 
run o left s twice x after b look o 
look o opposite v left s and a turn o around w right u twice x 
turn o right u thrice y after b look o around w right u twice x 
run o left s twice x and a run o opposite v left s twice x 
run o left s thrice y and a run o around w left s twice x 
look o right u thrice y and a turn o around w left s thrice y 
walk o thrice y after b run o opposite v left s 
look o around w left s and a turn o around w left s twice x 
walk o opposite v left s after b walk o opposite v left s thrice y 
run o opposite v left s twice x and a look o twice x 
turn o opposite v left s twice x and a turn o opposite v left s twice x 
walk o left s twice x and a walk o thrice y 
turn o left s after b run o around w left s twice x 
walk o opposite v right u and a look o opposite v right u twice x 
look o around w left s twice x after b turn o opposite v right u twice x 
run o around w right u and a turn o opposite v right u thrice y 
run o opposite v left s thrice y after b look o opposite v right u thrice y 
run o around w right u twice x after b turn o opposite v left s twice x 
walk o opposite v left s twice x and a look o around w right u 
run o opposite v right u twice x and a run o right u twice x 
run o and a run o opposite v left s 
run o after b run o 
look o right u and a turn o right u twice x 
turn o around w right u thrice y after b walk o around w right u 
jump o 
run o left s thrice y and a look o right u twice x 
look o opposite v right u thrice y after b look o opposite v right u twice x 
turn o around w right u and a turn o opposite v left s twice x 
look o right u twice x after b turn o opposite v right u twice x 
turn o around w left s twice x and a look o right u 
walk o opposite v right u and a turn o right u 
run o opposite v left s thrice y and a look o around w right u 
jump o 
walk o around w right u after b run o opposite v left s twice x 
look o around w left s twice x after b run o around w right u 
walk o right u thrice y after b walk o around w left s thrice y 
run o thrice y after b turn o opposite v left s 
look o opposite v right u twice x and a turn o around w left s thrice y 
run o left s twice x after b run o around w right u thrice y 
walk o opposite v right u twice x and a turn o opposite v right u twice x 
run o left s and a run o opposite v left s twice x 
jump o 
look o left s after b walk o around w left s twice x 
turn o right u thrice y and a look o opposite v left s twice x 
look o left s after b look o 
run o right u twice x after b look o around w right u twice x 
look o opposite v right u twice x and a run o around w left s thrice y 
walk o opposite v right u twice x after b walk o opposite v right u twice x 
turn o around w right u twice x after b look o around w right u thrice y 
run o opposite v right u twice x after b run o left s 
run o opposite v right u thrice y and a run o right u twice x 
turn o around w right u thrice y after b run o around w left s twice x 
turn o left s twice x and a look o left s 
run o opposite v left s twice x and a turn o opposite v left s twice x 
run o and a run o opposite v right u 
look o after b look o right u twice x 
look o right u thrice y and a look o around w right u thrice y 
walk o left s after b run o twice x 
run o opposite v right u thrice y after b turn o left s 
turn o around w right u twice x after b walk o opposite v right u twice x 
run o opposite v left s thrice y after b run o right u 
run o around w right u and a turn o opposite v right u twice x 
walk o opposite v left s after b look o opposite v left s 
jump o 
jump o 
walk o right u and a walk o right u thrice y 
turn o left s twice x and a walk o opposite v right u twice x 
run o opposite v left s thrice y after b walk o left s 
walk o around w left s thrice y after b look o opposite v right u 
turn o around w left s and a look o opposite v left s twice x 
turn o left s thrice y and a turn o right u 
look o after b run o left s twice x 
run o opposite v right u twice x and a run o around w right u 
walk o left s and a walk o left s 
walk o opposite v left s thrice y and a look o opposite v left s thrice y 
turn o right u thrice y and a walk o left s twice x 
turn o left s and a turn o around w left s thrice y 
turn o around w left s after b run o right u 
walk o right u twice x and a look o right u 
run o right u thrice y and a run o left s twice x 
run o opposite v right u and a turn o left s 
walk o around w left s thrice y and a run o around w right u twice x 
look o opposite v right u twice x and a walk o opposite v left s 
walk o around w left s and a look o opposite v left s 
run o right u and a turn o left s 
jump o 
turn o around w right u twice x and a walk o opposite v right u 
walk o around w right u thrice y after b walk o thrice y 
look o opposite v right u thrice y and a run o around w right u thrice y 
look o twice x after b walk o opposite v left s twice x 
look o opposite v left s twice x after b walk o opposite v right u 
jump o 
look o right u after b walk o around w left s twice x 
walk o left s thrice y after b walk o 
turn o opposite v right u thrice y and a run o around w right u thrice y 
walk o opposite v left s twice x and a walk o around w left s thrice y 
turn o opposite v right u thrice y and a look o left s thrice y 
turn o left s and a run o around w left s thrice y 
look o around w right u and a turn o opposite v left s thrice y 
walk o left s twice x after b turn o right u twice x 
turn o opposite v left s after b turn o around w right u 
run o opposite v right u twice x after b run o opposite v left s thrice y 
run o opposite v left s twice x after b run o left s twice x 
look o around w left s after b look o right u 
look o around w left s and a look o around w left s thrice y 
turn o around w right u after b walk o opposite v left s 
run o and a look o left s 
jump o 
walk o left s after b turn o left s 
walk o around w right u thrice y after b turn o opposite v left s twice x 
run o right u twice x after b run o opposite v left s twice x 
look o opposite v right u thrice y after b look o opposite v left s 
run o around w right u twice x and a run o around w right u 
turn o around w right u and a look o opposite v right u thrice y 
look o around w left s twice x after b walk o opposite v right u twice x 
jump o 
run o around w right u thrice y after b look o around w left s thrice y 
look o opposite v left s twice x after b walk o right u twice x 
walk o left s thrice y after b turn o around w left s 
walk o around w right u and a walk o thrice y 
look o right u thrice y after b look o opposite v right u thrice y 
run o opposite v right u thrice y after b run o left s 
turn o left s twice x and a run o left s 
turn o around w right u thrice y and a look o around w left s thrice y 
run o thrice y after b look o opposite v right u twice x 
look o around w left s and a look o around w right u thrice y 
walk o left s after b run o opposite v right u thrice y 
walk o left s thrice y after b walk o around w right u twice x 
run o opposite v left s after b look o opposite v left s twice x 
walk o left s twice x and a walk o left s twice x 
look o right u thrice y after b look o opposite v right u twice x 
look o right u twice x and a look o around w left s thrice y 
run o after b look o left s thrice y 
turn o opposite v right u twice x after b walk o twice x 
look o opposite v left s and a walk o opposite v left s 
walk o opposite v left s twice x and a turn o around w right u 
run o around w left s twice x after b run o opposite v right u 
jump o 
look o left s and a walk o around w right u thrice y 
run o after b look o right u twice x 
walk o around w left s twice x and a look o opposite v left s thrice y 
jump o 
look o around w left s twice x and a turn o opposite v right u thrice y 
turn o opposite v left s twice x after b run o opposite v left s thrice y 
walk o around w right u twice x and a run o opposite v left s 
walk o around w right u after b turn o opposite v right u twice x 
look o right u after b look o right u thrice y 
walk o left s twice x after b look o around w right u 
look o left s thrice y after b look o around w left s twice x 
jump o 
look o thrice y after b walk o left s 
look o left s twice x after b walk o opposite v right u 
walk o and a look o opposite v left s thrice y 
turn o opposite v right u thrice y and a look o right u twice x 
jump o 
look o around w left s and a run o twice x 
jump o 
turn o left s thrice y and a walk o left s thrice y 
look o right u after b run o opposite v right u thrice y 
jump o 
turn o opposite v left s thrice y and a run o opposite v right u 
turn o opposite v right u thrice y and a turn o around w right u 
walk o around w left s and a run o left s 
walk o around w right u thrice y after b walk o opposite v right u thrice y 
look o opposite v right u and a look o around w left s twice x 
jump o 
jump o 
look o right u twice x and a run o right u twice x 
look o around w right u twice x and a walk o around w right u 
look o left s twice x and a walk o right u twice x 
run o opposite v left s after b look o left s twice x 
look o opposite v left s thrice y after b look o left s twice x 
look o opposite v right u twice x and a run o thrice y 
walk o right u after b walk o around w left s 
look o around w left s thrice y and a look o around w left s thrice y 
run o left s after b turn o opposite v left s twice x 
jump o 
jump o 
walk o right u twice x after b run o around w left s twice x 
run o right u thrice y and a walk o right u 
turn o around w left s and a run o thrice y 
run o left s thrice y after b walk o around w left s thrice y 
run o opposite v left s thrice y and a walk o around w right u thrice y 
look o right u twice x after b turn o around w left s thrice y 
turn o opposite v right u after b walk o opposite v right u thrice y 
run o around w right u thrice y after b look o around w right u twice x 
walk o left s thrice y and a look o opposite v left s thrice y 
jump o 
look o around w left s twice x after b look o right u 
turn o around w right u thrice y and a walk o around w right u 
turn o right u thrice y after b walk o around w right u thrice y 
jump o 
walk o opposite v right u thrice y after b look o left s thrice y 
look o around w left s thrice y and a walk o left s 
look o thrice y and a run o right u thrice y 
turn o opposite v right u twice x and a run o around w left s twice x 
look o around w left s thrice y after b turn o around w left s 
look o right u twice x and a walk o opposite v right u thrice y 
turn o around w left s twice x and a walk o around w right u twice x 
run o opposite v right u twice x after b turn o right u twice x 
walk o left s thrice y after b look o opposite v left s twice x 
jump o 
walk o opposite v right u twice x after b run o left s thrice y 
walk o thrice y after b run o right u 
walk o left s and a look o opposite v left s twice x 
jump o 
turn o opposite v left s thrice y after b run o opposite v left s twice x 
turn o left s and a walk o opposite v right u thrice y 
run o left s thrice y and a walk o right u thrice y 
walk o left s thrice y after b look o around w left s twice x 
jump o 
look o opposite v right u after b turn o around w right u twice x 
walk o opposite v left s thrice y after b run o around w left s twice x 
run o right u thrice y after b walk o around w left s twice x 
turn o left s after b walk o opposite v right u 
turn o around w right u twice x after b look o opposite v left s 
walk o opposite v left s twice x and a walk o around w right u thrice y 
walk o and a look o around w right u twice x 
turn o opposite v left s twice x and a turn o around w right u 
jump o 
look o left s thrice y and a look o 
look o around w left s thrice y and a walk o around w left s thrice y 
walk o around w right u thrice y and a look o opposite v left s 
look o right u and a turn o opposite v right u thrice y 
run o opposite v right u twice x after b walk o opposite v right u 
run o opposite v left s twice x and a run o opposite v left s thrice y 
look o opposite v right u after b run o twice x 
run o around w left s thrice y and a run o around w right u 
turn o right u thrice y and a turn o opposite v right u thrice y 
turn o around w left s twice x after b turn o left s twice x 
run o right u after b turn o around w right u 
look o left s and a turn o opposite v right u 
run o around w right u thrice y and a walk o left s twice x 
run o around w right u after b walk o around w left s 
walk o left s twice x and a run o opposite v left s thrice y 
walk o after b run o around w right u 
run o right u thrice y after b walk o 
walk o opposite v right u thrice y and a run o around w left s 
look o around w left s after b turn o opposite v right u twice x 
jump o 
look o around w right u thrice y after b look o opposite v left s 
run o opposite v right u twice x and a turn o opposite v right u twice x 
walk o around w right u and a turn o left s thrice y 
run o opposite v right u thrice y and a turn o opposite v right u twice x 
walk o twice x and a walk o opposite v right u twice x 
look o right u twice x and a walk o right u thrice y 
look o around w right u twice x and a run o left s 
run o around w left s and a walk o left s twice x 
jump o 
turn o left s twice x and a walk o left s twice x 
look o right u twice x and a run o right u thrice y 
look o opposite v left s twice x and a run o right u twice x 
turn o right u twice x and a run o left s 
run o right u thrice y after b look o around w left s 
run o right u twice x and a walk o opposite v right u twice x 
walk o right u thrice y after b run o opposite v right u twice x 
run o right u thrice y and a look o twice x 
turn o left s thrice y after b look o around w left s thrice y 
look o around w left s twice x and a run o around w right u thrice y 
walk o opposite v left s after b walk o around w right u 
walk o opposite v left s after b walk o opposite v left s twice x 
jump o 
walk o thrice y and a turn o opposite v left s thrice y 
walk o opposite v left s after b walk o opposite v left s 
look o around w right u twice x and a run o left s twice x 
turn o right u twice x and a run o left s twice x 
look o opposite v right u and a run o around w left s thrice y 
run o opposite v left s thrice y after b run o opposite v right u 
run o twice x and a turn o around w left s thrice y 
run o around w left s thrice y and a look o around w left s thrice y 
turn o opposite v right u twice x and a walk o opposite v left s twice x 
run o opposite v left s twice x after b run o thrice y 
turn o around w right u thrice y and a walk o opposite v left s twice x 
run o right u and a run o left s twice x 
jump o 
look o and a walk o opposite v right u 
walk o opposite v right u twice x and a run o left s twice x 
run o left s thrice y and a turn o left s thrice y 
run o thrice y after b run o opposite v left s thrice y 
jump o 
walk o right u and a run o left s 
walk o twice x after b run o opposite v left s 
walk o opposite v right u thrice y after b walk o opposite v right u thrice y 
look o opposite v left s after b turn o right u thrice y 
run o around w left s and a run o opposite v left s thrice y 
turn o opposite v left s thrice y after b run o around w right u twice x 
walk o opposite v left s after b walk o left s twice x 
walk o opposite v right u and a run o around w right u 
look o left s and a run o right u twice x 
look o left s thrice y after b turn o left s thrice y 
run o around w left s thrice y after b walk o around w right u twice x 
walk o opposite v left s twice x and a look o around w right u thrice y 
jump o 
look o around w left s after b turn o left s thrice y 
look o left s twice x after b walk o around w right u twice x 
jump o 
run o around w left s thrice y after b look o left s twice x 
walk o opposite v right u twice x after b walk o opposite v right u 
look o left s twice x after b look o 
jump o 
jump o 
turn o opposite v right u twice x after b look o opposite v left s twice x 
look o twice x after b look o around w left s thrice y 
walk o opposite v left s twice x and a walk o left s thrice y 
look o around w right u thrice y after b look o around w right u twice x 
turn o left s twice x and a look o left s thrice y 
look o around w left s twice x after b walk o opposite v right u 
turn o around w right u twice x after b walk o opposite v left s twice x 
walk o left s twice x and a turn o left s thrice y 
run o right u and a turn o left s twice x 
turn o opposite v right u twice x after b turn o opposite v right u thrice y 
run o after b walk o opposite v right u thrice y 
jump o 
look o around w right u after b look o opposite v left s twice x 
run o left s twice x after b look o opposite v left s thrice y 
run o right u thrice y and a look o left s 
jump o 
run o right u twice x and a walk o opposite v right u 
turn o right u twice x and a turn o left s thrice y 
jump o 
walk o after b look o around w right u 
run o around w left s twice x and a run o around w left s twice x 
walk o left s twice x after b look o opposite v right u thrice y 
run o around w left s thrice y after b look o opposite v right u thrice y 
look o left s twice x after b turn o around w right u twice x 
turn o left s thrice y and a walk o opposite v left s twice x 
jump o 
turn o opposite v right u twice x and a look o around w left s 
run o opposite v left s and a run o left s twice x 
run o left s twice x after b walk o opposite v left s twice x 
look o opposite v left s twice x after b walk o around w right u 
turn o opposite v right u after b run o opposite v left s twice x 
walk o around w right u after b look o left s thrice y 
run o left s and a walk o left s twice x 
jump o 
look o left s twice x 
look o and a walk o right u twice x 
walk o right u thrice y and a walk o thrice y 
look o right u and a look o thrice y 
run o opposite v left s thrice y after b turn o left s twice x 
run o opposite v right u thrice y 
turn o right u thrice y after b run o left s thrice y 
run o around w right u and a walk o right u thrice y 
run o right u thrice y after b walk o opposite v left s twice x 
look o opposite v left s thrice y after b look o right u thrice y 
turn o opposite v left s and a turn o left s thrice y 
look o left s and a walk o opposite v left s 
look o right u and a turn o around w right u twice x 
turn o right u after b look o around w right u thrice y 
look o opposite v right u after b look o thrice y 
look o opposite v right u twice x and a look o right u twice x 
turn o opposite v right u thrice y and a turn o opposite v left s twice x 
run o right u after b look o left s thrice y 
walk o around w left s thrice y after b run o left s twice x 
walk o opposite v right u thrice y after b run o thrice y 
walk o around w right u after b run o around w right u twice x 
look o around w left s thrice y after b walk o opposite v left s 
walk o left s and a look o left s 
jump o 
run o right u twice x and a walk o opposite v left s twice x 
look o right u and a look o right u thrice y 
jump o 
run o right u and a turn o left s thrice y 
turn o around w left s thrice y and a look o right u thrice y 
turn o right u and a run o opposite v right u twice x 
walk o left s twice x and a run o around w left s 
run o right u after b run o around w right u 
turn o around w right u thrice y after b look o right u 
turn o left s after b turn o around w left s thrice y 
jump o 
walk o opposite v left s twice x after b turn o around w right u thrice y 
turn o right u twice x after b look o around w left s twice x 
turn o around w right u thrice y after b turn o opposite v left s twice x 
look o around w left s thrice y after b look o left s twice x 
walk o around w left s after b turn o right u 
run o around w left s and a run o opposite v right u 
walk o opposite v right u twice x and a turn o around w right u twice x 
walk o around w right u and a look o twice x 
look o around w left s and a turn o around w right u 
walk o opposite v left s thrice y after b run o left s thrice y 
jump o 
walk o right u after b walk o 
look o opposite v right u after b turn o opposite v right u twice x 
run o opposite v left s thrice y and a run o opposite v right u twice x 
jump o 
run o opposite v right u twice x and a walk o opposite v left s twice x 
turn o right u after b look o around w left s 
look o left s twice x after b look o right u twice x 
turn o opposite v left s thrice y and a look o left s thrice y 
run o around w right u twice x after b run o around w right u 
turn o around w left s after b run o thrice y 
look o opposite v left s twice x and a walk o right u thrice y 
run o opposite v left s and a run o opposite v right u thrice y 
turn o left s thrice y after b turn o left s twice x 
jump o 
walk o left s twice x and a look o opposite v right u thrice y 
run o around w right u thrice y after b look o right u twice x 
turn o around w left s thrice y after b look o opposite v left s thrice y 
turn o around w right u twice x and a look o around w right u thrice y 
walk o around w right u twice x and a walk o opposite v left s 
turn o around w right u thrice y after b turn o around w left s thrice y 
run o opposite v left s and a turn o around w left s 
turn o opposite v right u after b run o around w left s twice x 
run o opposite v left s after b look o opposite v right u twice x 
turn o around w left s twice x and a turn o around w right u twice x 
walk o left s twice x and a look o around w left s twice x 
jump o 
run o around w right u after b look o opposite v left s 
walk o and a run o left s 
look o opposite v right u thrice y after b turn o opposite v right u twice x 
run o left s twice x after b run o opposite v right u twice x 
look o thrice y after b run o around w left s 
look o right u twice x and a walk o opposite v right u twice x 
run o around w right u twice x after b run o opposite v right u thrice y 
walk o left s thrice y and a run o twice x 
look o twice x after b turn o around w left s thrice y 
look o left s thrice y after b walk o 
walk o around w right u and a walk o around w right u 
walk o opposite v right u twice x after b run o right u thrice y 
turn o opposite v right u and a walk o opposite v left s thrice y 
jump o 
look o twice x and a turn o around w left s 
walk o around w left s twice x after b run o right u 
run o left s and a turn o around w left s thrice y 
run o right u twice x and a turn o around w left s thrice y 
run o around w left s twice x and a turn o around w right u twice x 
look o around w right u twice x after b run o opposite v right u twice x 
walk o opposite v right u thrice y after b turn o opposite v left s thrice y 
look o right u twice x after b turn o right u thrice y 
look o opposite v left s twice x after b run o around w left s 
jump o 
turn o left s thrice y after b turn o opposite v left s twice x 
run o opposite v left s and a walk o opposite v right u twice x 
run o opposite v left s twice x after b look o around w left s thrice y 
run o around w right u after b walk o left s thrice y 
run o opposite v right u twice x and a walk o around w right u thrice y 
walk o thrice y after b walk o twice x 
turn o around w left s twice x after b look o opposite v left s thrice y 
jump o 
look o opposite v right u thrice y after b look o left s twice x 
turn o opposite v left s thrice y after b run o right u thrice y 
turn o around w left s and a walk o opposite v right u twice x 
run o right u after b turn o right u 
walk o around w left s twice x after b turn o right u twice x 
look o opposite v right u thrice y and a turn o opposite v left s thrice y 
look o around w right u and a look o left s thrice y 
walk o opposite v right u thrice y and a walk o around w left s twice x 
jump o 
run o around w right u twice x and a run o opposite v right u 
look o around w right u thrice y and a walk o opposite v right u twice x 
look o opposite v left s thrice y after b look o left s 
look o twice x after b run o opposite v left s 
look o opposite v right u twice x after b run o around w right u thrice y 
turn o left s and a turn o left s 
walk o opposite v left s thrice y after b walk o right u twice x 
run o left s thrice y after b walk o left s twice x 
look o around w left s after b turn o right u 
run o opposite v left s twice x after b look o left s 
turn o opposite v left s twice x after b turn o around w left s 
run o around w left s thrice y and a run o twice x 
run o around w right u and a walk o left s twice x 
run o right u thrice y after b look o twice x 
look o left s after b turn o around w left s 
jump o 
look o opposite v left s thrice y and a look o left s thrice y 
turn o around w right u twice x and a run o around w left s thrice y 
run o right u and a walk o around w left s twice x 
look o opposite v right u twice x and a look o opposite v right u twice x 
turn o opposite v left s and a look o thrice y 
jump o 
look o around w right u twice x and a turn o left s thrice y 
run o right u twice x and a run o opposite v left s twice x 
turn o opposite v right u thrice y after b look o left s 
look o around w right u thrice y after b turn o opposite v left s twice x 
look o opposite v left s thrice y and a run o around w left s twice x 
run o right u and a walk o right u 
run o around w right u twice x and a walk o opposite v right u thrice y 
jump o 
turn o around w right u twice x after b run o opposite v right u thrice y 
turn o right u thrice y after b walk o left s 
look o opposite v right u thrice y after b walk o around w left s thrice y 
turn o right u thrice y after b walk o opposite v right u 
jump o 
walk o and a turn o opposite v right u thrice y 
run o left s after b walk o 
look o around w right u twice x and a look o left s twice x 
jump o 
walk o around w left s twice x and a walk o 
run o around w left s twice x and a run o left s 
run o around w right u thrice y after b walk o around w right u thrice y 
look o opposite v left s and a walk o thrice y 
look o around w right u twice x after b run o opposite v left s thrice y 
jump o 
run o around w right u thrice y after b walk o opposite v right u 
look o right u and a run o opposite v right u twice x 
look o opposite v right u twice x and a run o opposite v right u twice x 
walk o opposite v left s after b walk o opposite v right u twice x 
walk o around w left s and a turn o around w right u twice x 
turn o opposite v left s twice x and a look o right u 
jump o 
turn o opposite v right u and a look o opposite v right u twice x 
run o twice x after b walk o around w right u 
look o around w right u twice x after b walk o opposite v left s twice x 
run o around w left s and a walk o 
look o opposite v left s and a turn o right u 
walk o around w right u after b run o opposite v right u thrice y 
walk o around w right u twice x after b walk o thrice y 
walk o left s thrice y after b run o twice x 
turn o opposite v right u twice x and a look o around w right u thrice y 
turn o around w left s and a turn o left s thrice y 
run o left s twice x and a run o around w right u 
walk o opposite v left s twice x after b walk o around w right u twice x 
look o left s thrice y after b turn o around w right u twice x 
turn o right u and a look o opposite v left s twice x 
run o right u after b run o around w right u thrice y 
run o left s thrice y after b look o left s twice x 
jump o 
jump o 
look o around w right u thrice y and a run o right u 
walk o left s thrice y after b turn o around w right u 
look o opposite v left s and a run o opposite v left s thrice y 
turn o right u twice x after b walk o right u thrice y 
jump o 
jump o 
jump o 
look o and a turn o around w right u thrice y 
run o right u twice x and a walk o right u 
turn o opposite v right u twice x after b look o right u 
turn o opposite v left s thrice y after b walk o around w right u thrice y 
jump o 
run o around w left s thrice y after b turn o left s twice x 
jump o 
turn o around w left s thrice y and a turn o opposite v right u twice x 
walk o after b walk o around w right u 
walk o around w left s twice x after b run o opposite v left s thrice y 
run o twice x after b run o around w left s twice x 
walk o opposite v right u after b turn o left s 
turn o right u twice x after b look o left s twice x 
jump o 
walk o after b walk o left s twice x 
walk o right u and a turn o opposite v right u 
turn o around w right u after b run o around w right u 
walk o around w right u after b turn o right u thrice y 
look o left s thrice y and a walk o around w right u twice x 
walk o and a run o left s thrice y 
look o opposite v right u thrice y and a run o opposite v left s twice x 
run o opposite v left s twice x after b walk o right u twice x 
turn o opposite v right u twice x and a walk o right u thrice y 
run o left s after b run o around w right u twice x 
look o left s twice x and a run o 
walk o opposite v right u after b walk o thrice y 
run o right u thrice y after b walk o opposite v left s thrice y 
look o and a look o opposite v left s twice x 
jump o 
turn o right u and a walk o around w left s twice x 
look o left s after b look o around w right u twice x 
jump o 
run o around w left s twice x and a run o left s twice x 
run o opposite v left s thrice y after b look o left s 
run o opposite v left s and a look o left s 
walk o around w left s and a walk o around w right u twice x 
run o opposite v left s thrice y and a turn o around w right u 
jump o 
run o around w left s twice x after b look o around w left s twice x 
look o thrice y after b look o opposite v right u thrice y 
run o opposite v left s after b look o opposite v right u 
jump o 
look o around w right u after b walk o left s 
walk o left s thrice y and a turn o around w left s thrice y 
run o around w right u thrice y after b run o right u thrice y 
turn o left s thrice y and a look o left s twice x 
turn o around w left s twice x after b run o right u 
run o left s twice x and a walk o around w right u thrice y 
turn o around w right u and a run o twice x 
jump o 
walk o after b look o opposite v left s 
turn o left s after b run o around w left s thrice y 
run o right u twice x after b run o around w right u twice x 
look o around w left s twice x after b look o 
jump o 
look o opposite v left s and a run o around w left s thrice y 
run o right u twice x after b look o left s twice x 
run o right u twice x and a look o around w left s 
turn o left s thrice y after b turn o around w right u thrice y 
walk o around w left s twice x after b turn o around w right u twice x 
jump o 
run o left s after b walk o right u twice x 
walk o left s thrice y after b walk o left s twice x 
run o around w left s thrice y and a walk o around w right u twice x 
walk o opposite v left s twice x and a turn o opposite v left s thrice y 
run o opposite v left s thrice y and a run o thrice y 
run o right u thrice y after b turn o opposite v left s 
turn o around w right u thrice y and a walk o right u 
run o opposite v right u twice x and a look o thrice y 
walk o left s and a run o left s twice x 
run o around w right u thrice y and a walk o right u twice x 
jump o 
walk o opposite v left s thrice y and a turn o around w left s 
turn o around w left s thrice y and a look o around w left s twice x 
run o around w left s after b run o left s twice x 
walk o around w left s and a walk o left s thrice y 
walk o twice x after b look o opposite v right u twice x 
walk o opposite v right u twice x and a look o right u thrice y 
walk o around w right u twice x and a turn o around w left s 
look o right u and a turn o around w right u thrice y 
run o around w left s twice x after b run o opposite v right u twice x 
run o thrice y and a walk o 
run o around w left s twice x after b turn o around w left s 
turn o right u after b look o left s 
walk o around w right u thrice y after b run o left s 
run o opposite v right u twice x after b walk o right u twice x 
turn o left s twice x after b look o opposite v left s thrice y 
look o right u thrice y after b walk o opposite v right u thrice y 
turn o around w right u thrice y and a look o around w left s 
turn o right u thrice y and a run o opposite v left s 
turn o around w right u thrice y after b look o 
turn o right u thrice y and a walk o opposite v right u twice x 
turn o around w left s thrice y and a look o opposite v right u thrice y 
turn o left s and a walk o around w right u twice x 
look o thrice y after b run o around w left s twice x 
walk o opposite v left s after b walk o left s thrice y 
run o opposite v left s thrice y and a turn o around w right u twice x 
look o around w left s after b turn o opposite v right u 
walk o opposite v left s and a look o opposite v right u thrice y 
look o around w right u after b turn o around w right u 
look o around w left s twice x after b look o right u thrice y 
run o opposite v left s twice x after b run o around w right u twice x 
look o around w right u twice x and a look o around w right u thrice y 
run o right u twice x and a look o opposite v left s thrice y 
look o right u thrice y and a walk o around w left s 
walk o opposite v left s thrice y and a turn o opposite v right u thrice y 
jump o 
look o left s after b turn o around w left s twice x 
turn o around w left s thrice y after b look o right u 
turn o left s thrice y and a run o opposite v right u 
jump o 
walk o left s and a look o 
walk o twice x after b look o left s 
walk o opposite v right u thrice y and a run o opposite v right u thrice y 
turn o around w right u thrice y after b run o around w left s thrice y 
look o left s twice x after b look o around w right u 
run o around w left s thrice y and a look o around w left s twice x 
look o opposite v left s and a walk o right u thrice y 
run o and a walk o 
walk o around w right u after b turn o opposite v right u thrice y 
walk o around w right u twice x after b look o around w left s twice x 
turn o opposite v right u twice x after b turn o left s thrice y 
run o right u and a look o around w right u thrice y 
look o thrice y and a look o opposite v right u 
turn o right u after b turn o around w right u thrice y 
run o opposite v left s after b run o left s thrice y 
turn o around w right u thrice y and a turn o opposite v left s 
look o twice x and a look o opposite v right u thrice y 
look o after b walk o thrice y 
run o around w left s twice x after b look o opposite v right u thrice y 
jump o 
walk o opposite v right u twice x after b look o right u 
look o opposite v left s and a run o right u thrice y 
run o opposite v right u and a run o around w left s 
run o opposite v left s twice x and a run o opposite v right u thrice y 
walk o around w right u thrice y and a run o twice x 
run o opposite v left s and a turn o opposite v left s twice x 
run o opposite v left s thrice y after b turn o around w right u thrice y 
run o left s and a look o opposite v left s twice x 
look o thrice y and a run o around w left s thrice y 
run o around w left s twice x after b turn o opposite v right u thrice y 
turn o right u twice x and a walk o right u 
turn o left s twice x after b look o left s thrice y 
turn o around w left s twice x after b turn o opposite v right u thrice y 
look o and a look o right u 
look o opposite v left s twice x and a run o opposite v right u twice x 
jump o 
turn o right u after b walk o opposite v right u thrice y 
run o around w left s after b run o thrice y 
turn o opposite v left s and a look o around w left s thrice y 
walk o left s thrice y after b run o left s thrice y 
run o around w right u and a run o around w right u thrice y 
look o right u and a turn o opposite v right u 
turn o right u thrice y and a turn o around w left s twice x 
run o opposite v left s twice x after b turn o around w left s twice x 
run o opposite v left s twice x and a turn o around w right u twice x 
look o opposite v left s and a turn o left s 
look o opposite v left s twice x and a look o opposite v left s thrice y 
run o around w right u twice x after b walk o around w right u twice x 
run o opposite v right u twice x after b walk o opposite v left s twice x 
run o opposite v left s and a run o right u 
walk o opposite v left s twice x and a walk o left s twice x 
look o right u and a look o around w right u 
look o opposite v left s thrice y and a walk o right u 
walk o and a run o opposite v right u 
walk o opposite v right u twice x and a run o opposite v left s thrice y 
walk o around w left s after b walk o right u twice x 
look o opposite v right u twice x after b walk o right u twice x 
walk o twice x and a walk o opposite v left s twice x 
walk o thrice y and a look o twice x 
look o opposite v left s thrice y after b run o around w right u twice x 
walk o opposite v right u thrice y after b look o opposite v left s twice x 
jump o 
walk o opposite v right u twice x after b look o right u twice x 
look o left s thrice y and a run o 
look o around w left s twice x after b turn o opposite v right u 
jump o 
turn o around w left s twice x after b walk o twice x 
run o thrice y after b run o around w left s thrice y 
run o right u thrice y after b turn o opposite v right u thrice y 
jump o 
turn o left s thrice y and a turn o around w right u thrice y 
run o thrice y and a look o thrice y 
run o left s and a walk o 
run o around w left s twice x after b walk o twice x 
look o opposite v right u twice x after b look o left s twice x 
run o left s twice x and a walk o opposite v left s twice x 
turn o right u twice x after b walk o around w right u 
walk o around w right u and a run o around w right u 
run o opposite v left s thrice y after b run o left s twice x 
run o twice x after b run o around w left s thrice y 
run o after b walk o around w left s twice x 
walk o around w left s and a run o opposite v right u 
turn o left s twice x after b turn o opposite v left s twice x 
look o right u and a look o opposite v left s twice x 
walk o opposite v left s and a walk o twice x 
look o left s and a run o opposite v right u thrice y 
look o opposite v right u twice x after b walk o left s twice x 
jump o 
run o opposite v right u thrice y and a look o around w left s twice x 
run o around w right u twice x and a walk o around w right u twice x 
run o around w right u thrice y after b walk o twice x 
look o left s and a run o left s thrice y 
run o around w right u and a run o right u 
look o opposite v right u after b look o right u twice x 
walk o opposite v left s thrice y and a turn o around w right u thrice y 
jump o 
walk o thrice y after b turn o opposite v left s thrice y 
run o right u thrice y after b run o opposite v left s twice x 
walk o twice x and a look o right u 
walk o around w left s twice x after b look o 
walk o right u thrice y after b run o right u 
look o twice x after b look o around w left s 
turn o around w left s after b turn o opposite v left s 
turn o around w right u twice x and a walk o around w left s twice x 
look o opposite v right u twice x after b run o twice x 
turn o around w right u thrice y after b walk o left s twice x 
look o around w left s twice x and a turn o right u thrice y 
run o opposite v left s after b run o right u thrice y 
turn o left s twice x and a run o opposite v right u thrice y 
walk o around w right u twice x after b turn o opposite v left s thrice y 
run o around w left s twice x and a turn o left s twice x 
run o left s thrice y and a look o around w left s 
run o left s after b look o 
look o opposite v right u and a look o opposite v left s 
walk o opposite v right u thrice y and a walk o around w left s 
jump o 
turn o around w left s twice x after b walk o around w right u thrice y 
look o opposite v left s after b walk o right u twice x 
turn o opposite v left s thrice y and a turn o around w right u twice x 
look o opposite v right u thrice y after b walk o 
look o opposite v right u thrice y after b walk o opposite v right u thrice y 
run o opposite v right u twice x after b run o 
jump o 
walk o right u after b turn o left s twice x 
look o opposite v left s after b look o opposite v right u twice x 
walk o thrice y and a turn o right u 
walk o around w right u thrice y and a look o opposite v right u twice x 
turn o opposite v right u thrice y and a walk o opposite v left s 
jump o 
jump o 
walk o thrice y and a turn o left s thrice y 
walk o around w right u twice x after b run o around w left s 
look o left s twice x and a run o opposite v right u thrice y 
look o left s thrice y after b look o twice x 
turn o around w left s twice x and a look o opposite v left s twice x 
turn o right u twice x after b run o around w left s twice x 
run o opposite v left s thrice y and a run o left s thrice y 
turn o opposite v left s and a walk o opposite v right u twice x 
walk o opposite v left s after b look o opposite v left s thrice y 
walk o left s thrice y after b look o around w left s 
turn o right u after b turn o around w left s 
run o opposite v right u and a walk o around w right u thrice y 
look o around w right u after b run o around w left s twice x 
walk o and a look o 
walk o around w left s thrice y and a look o left s thrice y 
turn o around w left s thrice y after b look o around w left s thrice y 
run o around w left s and a run o around w right u 
walk o around w right u twice x and a turn o around w right u 
turn o right u twice x after b look o around w right u twice x 
look o around w right u twice x after b look o left s 
turn o around w left s and a walk o right u twice x 
look o and a look o left s thrice y 
turn o left s twice x and a turn o left s twice x 
turn o around w left s twice x after b walk o right u 
run o opposite v left s twice x and a look o opposite v right u 
turn o opposite v left s twice x and a turn o opposite v right u twice x 
turn o around w left s after b turn o opposite v left s thrice y 
turn o opposite v left s thrice y after b turn o around w right u 
turn o opposite v right u and a run o opposite v right u thrice y 
walk o twice x after b walk o opposite v right u thrice y 
turn o around w left s twice x and a walk o 
walk o left s twice x after b run o around w left s 
turn o right u and a run o opposite v right u thrice y 
walk o right u thrice y and a turn o opposite v right u 
run o right u thrice y after b turn o around w right u thrice y 
walk o opposite v left s thrice y and a look o around w right u 
look o around w left s after b run o around w left s thrice y 
look o around w left s thrice y and a look o opposite v right u 
walk o right u thrice y after b walk o opposite v right u 
walk o opposite v left s twice x after b look o opposite v right u thrice y 
walk o left s thrice y and a look o opposite v right u 
walk o around w right u after b run o around w right u thrice y 
run o thrice y after b look o thrice y 
run o around w left s twice x after b run o right u 
look o around w left s twice x and a walk o opposite v left s twice x 
run o opposite v left s thrice y and a look o left s 
run o opposite v left s twice x after b look o around w right u twice x 
walk o opposite v right u after b look o around w left s twice x 
jump o 
jump o 
run o right u twice x and a run o opposite v right u 
look o after b turn o around w right u thrice y 
run o opposite v left s twice x and a look o around w left s 
walk o around w right u twice x after b look o opposite v right u 
walk o around w right u after b run o opposite v left s thrice y 
turn o left s twice x and a turn o opposite v right u thrice y 
run o after b run o around w right u 
run o around w left s after b look o opposite v right u thrice y 
look o twice x after b walk o right u 
look o opposite v left s after b turn o opposite v right u 
walk o opposite v left s thrice y and a run o left s 
jump o 
turn o opposite v left s after b turn o left s thrice y 
look o thrice y after b turn o opposite v right u thrice y 
turn o around w right u thrice y after b walk o right u 
turn o around w left s twice x after b turn o opposite v left s thrice y 
run o opposite v right u thrice y after b look o opposite v left s 
look o around w right u twice x after b turn o around w left s 
walk o opposite v left s thrice y after b turn o left s 
look o after b run o right u twice x 
look o around w right u thrice y and a run o right u thrice y 
look o around w right u after b walk o opposite v right u thrice y 
jump o 
look o left s thrice y and a run o around w right u 
jump o 
jump o 
look o around w right u twice x after b run o around w right u 
walk o opposite v right u twice x 
run o left s and a run o left s 
walk o around w left s thrice y and a turn o right u twice x 
walk o around w right u after b walk o around w right u 
jump o 
turn o around w right u thrice y and a run o left s twice x 
run o right u twice x and a turn o left s thrice y 
turn o around w right u thrice y and a look o left s thrice y 
jump o 
look o around w left s twice x and a look o left s twice x 
jump o 
turn o around w left s thrice y after b walk o around w left s thrice y 
look o around w left s thrice y after b walk o around w right u 
turn o opposite v right u after b turn o right u 
run o around w left s and a run o around w left s 
walk o left s twice x and a look o twice x 
walk o opposite v left s twice x after b walk o left s 
run o opposite v right u after b turn o opposite v left s 
look o right u and a run o right u 
look o opposite v right u thrice y after b turn o right u twice x 
look o right u thrice y and a walk o left s twice x 
turn o opposite v left s twice x and a turn o around w left s thrice y 
look o opposite v right u thrice y and a turn o opposite v right u thrice y 
turn o around w right u and a turn o opposite v right u thrice y 
turn o opposite v left s twice x after b run o right u twice x 
run o left s after b turn o opposite v right u 
look o twice x and a walk o twice x 
walk o thrice y after b walk o opposite v left s twice x 
run o opposite v right u twice x after b look o opposite v left s twice x 
run o right u after b look o right u thrice y 
walk o around w left s and a walk o opposite v right u twice x 
walk o around w right u twice x after b look o opposite v left s 
run o and a look o right u twice x 
turn o left s twice x after b look o opposite v right u 
turn o around w right u thrice y after b walk o around w left s thrice y 
look o and a run o around w right u thrice y 
walk o around w right u twice x and a turn o around w left s twice x 
walk o around w right u thrice y and a walk o left s twice x 
run o right u twice x after b run o right u thrice y 
look o twice x and a run o right u twice x 
walk o twice x and a run o 
walk o around w right u thrice y after b turn o around w left s twice x 
walk o right u thrice y after b look o opposite v left s twice x 
turn o around w right u thrice y and a walk o right u thrice y 
look o opposite v left s thrice y and a turn o right u thrice y 
run o left s thrice y and a look o left s 
look o twice x after b walk o right u twice x 
look o opposite v left s and a run o opposite v right u thrice y 
turn o right u twice x and a walk o right u twice x 
run o opposite v left s after b walk o around w left s thrice y 
run o left s thrice y after b walk o right u twice x 
walk o around w right u twice x and a turn o opposite v right u 
jump o 
run o opposite v left s after b run o around w left s 
walk o right u thrice y and a look o twice x 
walk o around w left s after b walk o thrice y 
walk o opposite v left s twice x and a walk o opposite v right u 
look o and a turn o left s twice x 
run o left s twice x and a turn o left s twice x 
turn o right u twice x after b run o right u thrice y 
walk o opposite v right u thrice y after b walk o around w left s 
turn o around w right u after b walk o 
turn o around w left s thrice y and a turn o left s twice x 
turn o opposite v right u thrice y and a run o around w right u 
walk o left s after b walk o opposite v left s thrice y 
look o left s and a run o around w left s 
look o around w right u twice x and a walk o right u thrice y 
look o opposite v left s thrice y and a turn o left s thrice y 
walk o twice x after b run o around w right u 
run o opposite v left s after b look o 
walk o opposite v right u thrice y and a walk o opposite v left s 
turn o opposite v right u twice x and a walk o around w right u thrice y 
run o opposite v left s twice x and a run o thrice y 
look o left s twice x after b look o opposite v right u twice x 
look o around w left s thrice y after b run o around w left s 
turn o opposite v left s thrice y after b look o right u 
walk o around w left s and a run o around w right u thrice y 
walk o opposite v right u thrice y after b look o around w left s twice x 
look o opposite v right u after b look o around w left s twice x 
run o around w right u and a walk o right u 
look o around w left s after b walk o right u 
look o twice x after b walk o around w left s twice x 
turn o around w left s and a turn o around w left s thrice y 
turn o opposite v left s thrice y after b turn o opposite v left s twice x 
run o opposite v left s after b turn o left s 
walk o left s thrice y and a run o left s 
walk o opposite v left s and a turn o around w right u twice x 
walk o around w left s twice x after b run o twice x 
turn o opposite v left s thrice y and a look o thrice y 
look o around w left s twice x and a look o left s 
walk o left s thrice y after b look o opposite v right u thrice y 
walk o opposite v right u thrice y and a look o right u twice x 
look o around w right u thrice y and a run o left s twice x 
look o opposite v right u twice x and a walk o opposite v left s thrice y 
look o opposite v left s thrice y and a run o opposite v right u twice x 
look o opposite v right u twice x and a walk o right u twice x 
run o opposite v right u after b walk o around w right u twice x 
turn o opposite v left s twice x and a run o around w right u 
walk o right u and a run o around w left s thrice y 
walk o left s twice x after b run o around w left s twice x 
turn o around w left s thrice y and a run o opposite v right u 
look o left s thrice y after b walk o right u 
run o twice x and a look o right u thrice y 
jump o 
look o opposite v left s thrice y and a run o left s thrice y 
turn o left s twice x after b turn o right u 
turn o opposite v right u thrice y and a run o right u thrice y 
walk o around w left s twice x and a look o around w right u 
look o opposite v left s and a walk o opposite v left s twice x 
look o left s twice x after b walk o around w left s thrice y 
turn o opposite v right u after b turn o around w left s thrice y 
turn o around w right u twice x and a walk o opposite v left s thrice y 
run o opposite v left s after b look o right u twice x 
look o left s twice x and a walk o 
turn o around w left s thrice y and a walk o thrice y 
walk o left s twice x and a walk o left s thrice y 
walk o left s and a look o opposite v left s thrice y 
walk o around w right u after b walk o opposite v left s twice x 
run o opposite v right u thrice y and a walk o around w right u thrice y 
walk o opposite v right u thrice y and a walk o opposite v right u thrice y 
turn o opposite v right u and a look o around w left s thrice y 
look o twice x and a run o opposite v left s twice x 
turn o left s and a run o thrice y 
jump o 
turn o opposite v left s and a turn o opposite v right u 
run o around w left s after b run o opposite v right u 
run o around w right u twice x and a walk o 
run o opposite v left s twice x and a run o right u 
turn o around w left s twice x 
look o after b run o thrice y 
walk o twice x and a turn o opposite v left s thrice y 
turn o right u thrice y after b run o opposite v right u thrice y 
walk o opposite v right u and a run o around w right u thrice y 
jump o 
run o opposite v right u thrice y after b run o around w left s thrice y 
run o left s after b turn o right u twice x 
turn o around w left s twice x and a walk o around w right u 
turn o around w right u twice x and a walk o around w left s 
look o opposite v left s thrice y after b run o opposite v right u thrice y 
run o opposite v left s twice x after b walk o around w right u twice x 
walk o opposite v left s after b walk o around w left s 
jump o 
turn o around w left s and a run o twice x 
walk o right u twice x and a look o opposite v right u thrice y 
walk o around w left s twice x and a run o left s twice x 
walk o thrice y and a run o thrice y 
look o around w right u twice x and a run o 
run o around w right u after b run o opposite v right u twice x 
look o around w left s after b walk o twice x 
walk o around w left s thrice y and a run o thrice y 
walk o left s and a run o around w left s thrice y 
walk o left s twice x and a walk o around w right u 
run o around w left s twice x and a run o opposite v right u 
jump o 
turn o opposite v left s twice x after b walk o right u thrice y 
walk o opposite v right u thrice y and a run o around w right u thrice y 
look o left s thrice y and a look o around w right u twice x 
walk o around w right u thrice y after b run o around w right u twice x 
look o left s twice x after b walk o opposite v right u twice x 
look o around w right u after b turn o right u thrice y 
turn o left s thrice y and a look o around w right u 
look o left s thrice y and a turn o opposite v left s twice x 
run o opposite v right u thrice y after b run o twice x 
run o opposite v left s twice x after b turn o right u thrice y 
look o opposite v right u thrice y and a look o left s twice x 
walk o left s twice x after b look o around w left s 
run o opposite v left s and a turn o around w right u 
turn o left s twice x after b run o right u twice x 
run o twice x and a run o around w left s 
run o opposite v left s after b walk o right u twice x 
look o left s twice x after b turn o around w right u 
run o around w left s twice x after b turn o left s 
look o right u after b look o left s twice x 
turn o right u and a run o opposite v left s 
run o opposite v left s twice x and a walk o around w left s 
run o opposite v left s thrice y after b run o right u thrice y 
walk o twice x and a run o opposite v right u twice x 
turn o around w left s and a run o right u twice x 
turn o right u and a run o 
look o opposite v left s thrice y after b turn o opposite v right u thrice y 
walk o left s thrice y and a turn o right u thrice y 
run o right u after b run o opposite v left s thrice y 
walk o right u thrice y after b run o left s twice x 
turn o opposite v right u twice x after b run o thrice y 
run o opposite v right u thrice y and a run o around w right u 
jump o 
turn o around w left s thrice y after b turn o opposite v left s 
run o around w right u thrice y after b look o opposite v left s twice x 
run o thrice y and a look o left s 
jump o 
run o around w left s thrice y and a look o around w right u 
walk o left s thrice y and a turn o around w right u 
turn o opposite v left s twice x and a turn o right u thrice y 
run o around w right u after b walk o opposite v right u 
jump o 
run o opposite v right u twice x after b turn o around w right u 
run o around w right u twice x and a look o opposite v left s 
turn o opposite v right u twice x and a run o opposite v right u 
run o opposite v right u twice x after b turn o around w right u thrice y 
run o twice x and a look o around w left s 
look o around w left s thrice y and a look o around w right u twice x 
look o right u and a run o 
walk o twice x after b walk o right u thrice y 
turn o opposite v left s thrice y after b turn o opposite v right u thrice y 
walk o around w left s twice x after b turn o around w right u thrice y 
run o around w right u twice x after b walk o right u twice x 
turn o left s twice x and a look o opposite v left s thrice y 
look o and a turn o right u thrice y 
run o left s thrice y after b walk o twice x 
turn o around w left s and a look o opposite v right u 
walk o opposite v right u thrice y after b run o right u thrice y 
turn o opposite v left s and a walk o around w right u 
walk o left s thrice y after b look o right u twice x 
turn o around w left s thrice y after b turn o opposite v left s thrice y 
run o opposite v right u thrice y and a walk o opposite v left s twice x 
run o opposite v left s twice x after b walk o left s thrice y 
look o right u twice x after b walk o 
turn o opposite v right u twice x after b walk o opposite v left s twice x 
turn o around w right u and a look o right u 
walk o opposite v right u thrice y after b look o left s 
jump o 
look o opposite v left s and a look o right u twice x 
run o opposite v right u thrice y after b run o thrice y 
look o thrice y and a turn o opposite v right u 
look o around w left s and a turn o opposite v right u thrice y 
walk o left s twice x and a turn o opposite v left s twice x 
walk o opposite v right u thrice y after b walk o around w left s twice x 
look o around w left s thrice y and a turn o opposite v left s thrice y 
run o around w left s after b walk o opposite v right u twice x 
run o after b look o right u thrice y 
run o opposite v left s twice x after b walk o right u thrice y 
walk o right u twice x after b walk o right u thrice y 
walk o left s thrice y and a turn o opposite v left s twice x 
walk o around w right u twice x and a turn o left s twice x 
walk o around w right u thrice y after b walk o around w right u twice x 
run o around w left s twice x and a run o twice x 
turn o left s twice x and a turn o left s thrice y 
walk o left s and a turn o around w right u twice x 
walk o right u and a turn o around w left s twice x 
run o thrice y after b walk o left s thrice y 
look o after b look o left s twice x 
run o twice x after b look o opposite v left s 
jump o 
run o around w right u and a look o around w right u thrice y 
look o opposite v right u thrice y and a look o around w right u thrice y 
look o right u thrice y and a look o right u twice x 
walk o around w left s after b turn o right u twice x 
look o around w left s after b look o opposite v left s twice x 
look o opposite v right u twice x and a walk o around w left s twice x 
look o around w left s twice x after b run o around w right u twice x 
walk o opposite v right u thrice y after b look o left s twice x 
turn o left s twice x and a run o around w right u twice x 
turn o opposite v right u twice x and a walk o opposite v left s thrice y 
walk o around w left s after b run o right u 
jump o 
run o left s after b walk o around w right u twice x 
turn o left s twice x after b run o opposite v right u thrice y 
turn o right u thrice y after b run o thrice y 
turn o opposite v right u thrice y and a turn o left s thrice y 
turn o around w right u and a turn o around w right u twice x 
jump o 
run o opposite v left s thrice y and a look o around w left s thrice y 
look o right u after b run o around w right u thrice y 
look o opposite v left s twice x after b walk o thrice y 
turn o left s twice x and a run o around w left s twice x 
look o twice x after b turn o left s 
look o right u twice x after b look o right u 
run o opposite v right u thrice y and a turn o right u thrice y 
walk o opposite v right u thrice y and a run o right u twice x 
look o opposite v left s twice x and a walk o twice x 
turn o around w right u twice x after b walk o around w right u twice x 
run o left s after b walk o twice x 
look o and a walk o right u thrice y 
walk o left s and a turn o around w left s thrice y 
walk o thrice y after b run o opposite v left s thrice y 
run o opposite v right u thrice y after b walk o right u thrice y 
walk o right u and a look o opposite v right u thrice y 
run o left s thrice y and a turn o opposite v left s thrice y 
run o thrice y after b look o around w left s thrice y 
look o right u and a walk o around w left s twice x 
walk o right u and a look o left s 
turn o opposite v left s twice x and a walk o around w right u 
look o and a look o thrice y 
walk o left s thrice y and a walk o opposite v left s thrice y 
look o opposite v left s twice x after b run o opposite v left s thrice y 
jump o 
run o left s after b look o around w right u twice x 
walk o around w left s and a turn o opposite v left s thrice y 
turn o opposite v left s and a walk o left s twice x 
run o left s twice x and a look o around w left s 
run o left s twice x and a turn o around w left s thrice y 
walk o and a run o opposite v right u thrice y 
turn o opposite v left s twice x and a run o around w right u thrice y 
look o opposite v right u thrice y and a turn o left s twice x 
look o around w left s thrice y and a run o opposite v right u thrice y 
run o opposite v right u twice x and a look o opposite v left s twice x 
look o right u thrice y and a turn o left s 
run o around w right u twice x and a look o around w right u twice x 
turn o opposite v left s twice x and a run o left s thrice y 
look o around w right u twice x and a run o around w right u 
walk o left s twice x and a run o around w right u 
jump o 
run o around w right u twice x after b walk o left s thrice y 
walk o opposite v right u twice x and a turn o right u 
turn o left s and a look o opposite v left s thrice y 
jump o 
look o twice x and a turn o opposite v right u 
run o around w left s after b look o twice x 
turn o around w left s after b look o right u twice x 
look o twice x and a turn o around w right u thrice y 
run o opposite v right u thrice y after b walk o around w right u 
walk o left s and a walk o left s thrice y 
look o thrice y after b turn o around w left s thrice y 
look o left s thrice y after b run o opposite v right u 
turn o around w right u twice x after b walk o around w left s 
run o around w right u and a walk o opposite v right u twice x 
look o left s thrice y after b walk o around w left s thrice y 
turn o opposite v right u thrice y and a walk o left s thrice y 
turn o around w right u after b look o around w left s 
walk o opposite v left s twice x after b walk o left s twice x 
walk o thrice y after b look o opposite v right u 
jump o 
turn o left s thrice y and a walk o opposite v right u twice x 
run o left s thrice y and a run o left s twice x 
walk o right u twice x and a walk o opposite v left s thrice y 
run o left s after b walk o opposite v right u 
turn o left s thrice y and a turn o around w right u twice x 
walk o around w right u twice x after b walk o left s 
run o around w left s thrice y after b turn o around w right u 
walk o opposite v right u and a run o twice x 
look o opposite v left s thrice y and a turn o opposite v right u 
run o left s after b look o opposite v right u 
jump o 
run o opposite v left s after b run o 
run o opposite v right u thrice y and a walk o opposite v right u thrice y 
turn o right u and a run o twice x 
look o left s thrice y and a run o around w right u thrice y 
run o left s and a turn o around w right u 
turn o around w left s twice x after b run o left s 
turn o opposite v right u and a walk o around w left s 
walk o around w left s thrice y and a run o 
turn o left s twice x and a turn o right u twice x 
run o right u thrice y and a look o opposite v right u 
look o around w right u twice x and a turn o right u 
turn o opposite v right u thrice y after b look o around w left s thrice y 
walk o after b walk o opposite v right u 
walk o opposite v right u twice x and a look o thrice y 
look o left s thrice y and a walk o around w left s twice x 
walk o opposite v right u after b walk o right u thrice y 
walk o opposite v left s after b walk o 
look o around w right u twice x and a run o opposite v left s 
run o opposite v right u twice x and a run o around w left s thrice y 
run o left s after b run o opposite v left s twice x 
turn o opposite v left s twice x after b walk o opposite v left s 
jump o 
look o left s thrice y and a run o left s 
walk o twice x after b walk o 
turn o left s twice x and a look o opposite v left s twice x 
turn o around w right u thrice y after b turn o around w left s twice x 
look o opposite v right u and a look o opposite v right u thrice y 
look o opposite v left s twice x after b look o around w right u 
look o right u thrice y after b look o left s thrice y 
walk o opposite v left s and a look o right u thrice y 
turn o right u thrice y after b walk o opposite v right u thrice y 
look o opposite v right u after b walk o around w left s twice x 
run o right u after b turn o around w right u twice x 
look o around w left s thrice y after b run o left s twice x 
run o opposite v left s after b walk o left s thrice y 
walk o opposite v right u thrice y after b walk o around w right u twice x 
jump o 
walk o right u twice x and a look o around w left s thrice y 
turn o opposite v right u thrice y after b walk o thrice y 
jump o 
run o around w left s twice x after b walk o left s twice x 
jump o 
run o left s after b turn o right u 
look o around w left s after b run o twice x 
run o left s twice x after b walk o right u thrice y 
turn o right u twice x after b run o left s thrice y 
walk o opposite v left s thrice y and a run o around w left s 
look o right u after b look o right u 
look o right u and a look o opposite v right u 
run o opposite v right u after b run o opposite v left s twice x 
walk o right u thrice y after b walk o around w right u twice x 
run o right u twice x and a look o right u thrice y 
look o opposite v left s thrice y after b walk o around w right u 
jump o 
turn o around w right u twice x after b look o opposite v right u twice x 
look o opposite v left s twice x and a run o right u thrice y 
walk o twice x and a look o around w left s thrice y 
turn o around w left s 
walk o right u after b turn o opposite v right u 
look o opposite v right u twice x and a look o right u thrice y 
run o opposite v right u and a run o opposite v right u thrice y 
run o left s thrice y after b run o around w left s 
run o around w left s twice x after b turn o opposite v left s twice x 
run o after b run o opposite v right u twice x 
run o right u twice x after b walk o left s twice x 
turn o around w right u after b look o opposite v left s 
walk o opposite v left s twice x after b look o twice x 
run o and a run o around w left s 
run o opposite v left s twice x after b look o thrice y 
walk o around w left s twice x after b walk o around w left s thrice y 
look o around w left s after b look o opposite v left s thrice y 
walk o left s thrice y and a turn o opposite v right u twice x 
run o opposite v right u after b walk o around w left s thrice y 
run o opposite v left s and a walk o opposite v right u 
turn o opposite v right u thrice y and a run o left s 
turn o around w right u twice x and a walk o left s thrice y 
look o around w left s after b walk o opposite v right u 
walk o opposite v left s thrice y after b look o right u 
turn o left s thrice y and a run o right u 
walk o around w left s after b turn o opposite v right u 
run o opposite v right u after b run o right u twice x 
run o right u thrice y after b run o opposite v right u 
jump o 
look o opposite v left s twice x after b walk o opposite v left s thrice y 
look o thrice y after b walk o thrice y 
jump o 
walk o left s thrice y after b walk o left s thrice y 
run o right u twice x and a walk o twice x 
walk o around w right u and a run o opposite v left s thrice y 
run o around w right u twice x and a turn o around w left s thrice y 
walk o right u thrice y after b walk o opposite v left s thrice y 
look o right u thrice y and a walk o around w right u thrice y 
walk o opposite v right u thrice y after b run o opposite v left s 
run o opposite v left s thrice y after b turn o left s 
turn o around w right u thrice y and a turn o left s thrice y 
look o right u thrice y and a run o twice x 
run o after b run o right u thrice y 
look o twice x after b run o opposite v left s twice x 
look o right u and a run o opposite v left s twice x 
run o left s twice x after b look o left s thrice y 
look o opposite v left s twice x and a run o around w right u thrice y 
look o right u twice x after b look o opposite v right u twice x 
run o around w right u after b look o left s 
turn o around w right u twice x and a run o around w right u twice x 
jump o 
turn o opposite v right u twice x after b run o left s thrice y 
run o opposite v right u after b look o opposite v left s twice x 
walk o around w left s twice x after b walk o opposite v left s twice x 
jump o 
turn o around w left s after b run o around w right u twice x 
look o around w left s twice x after b run o right u thrice y 
look o twice x after b turn o right u thrice y 
run o left s thrice y and a look o right u 
look o around w right u thrice y and a walk o opposite v left s twice x 
walk o opposite v left s and a look o around w left s thrice y 
run o left s twice x and a walk o opposite v left s 
look o opposite v left s after b run o opposite v left s 
walk o around w right u twice x after b run o right u thrice y 
turn o opposite v right u thrice y after b walk o around w left s 
turn o opposite v right u and a run o left s twice x 
look o left s after b walk o 
walk o around w right u and a look o left s twice x 
walk o left s thrice y and a turn o opposite v right u 
walk o opposite v left s thrice y after b look o opposite v right u twice x 
jump o 
turn o right u twice x and a walk o 
walk o thrice y after b look o around w right u thrice y 
turn o around w right u and a look o opposite v left s 
run o thrice y after b turn o opposite v right u thrice y 
walk o around w right u and a turn o opposite v right u 
turn o opposite v right u thrice y and a walk o twice x 
look o opposite v left s thrice y and a turn o around w left s thrice y 
jump o 
turn o opposite v right u twice x and a run o around w left s 
walk o right u twice x after b run o opposite v left s twice x 
run o right u twice x and a turn o left s twice x 
jump o 
run o thrice y after b turn o around w right u twice x 
turn o opposite v left s after b run o left s twice x 
run o right u twice x after b walk o 
jump o 
run o opposite v right u thrice y after b look o 
walk o opposite v left s thrice y after b run o opposite v left s 
turn o opposite v left s twice x after b look o right u twice x 
walk o around w right u thrice y and a look o left s 
run o thrice y and a run o opposite v right u thrice y 
look o opposite v right u after b turn o opposite v right u thrice y 
run o right u twice x and a turn o opposite v left s twice x 
run o right u and a turn o around w left s thrice y 
walk o right u thrice y after b run o opposite v right u thrice y 
look o opposite v left s thrice y 
look o right u twice x after b run o opposite v right u 
look o after b walk o opposite v right u 
look o around w right u thrice y after b walk o around w left s thrice y 
run o left s twice x and a look o left s twice x 
run o twice x after b walk o around w right u twice x 
turn o right u thrice y after b look o 
look o left s thrice y and a walk o opposite v right u twice x 
turn o around w left s after b run o right u thrice y 
jump o 
turn o opposite v right u thrice y after b turn o around w left s twice x 
look o left s twice x after b walk o 
walk o around w right u thrice y after b look o thrice y 
turn o left s twice x and a walk o around w right u thrice y 
run o opposite v right u and a run o around w right u thrice y 
run o opposite v left s twice x after b turn o around w left s thrice y 
walk o right u after b run o around w left s 
walk o opposite v right u and a look o around w right u twice x 
turn o around w right u thrice y and a run o left s 
turn o around w left s thrice y and a turn o left s 
look o thrice y and a run o around w left s twice x 
walk o thrice y and a turn o right u twice x 
run o opposite v left s thrice y after b turn o opposite v right u twice x 
walk o around w left s twice x and a look o opposite v left s twice x 
look o opposite v right u thrice y after b look o right u 
look o around w right u thrice y after b turn o right u 
look o opposite v left s thrice y and a run o around w right u twice x 
walk o opposite v left s thrice y after b run o twice x 
look o opposite v left s and a look o opposite v right u 
jump o 
walk o around w right u twice x after b walk o opposite v right u 
look o opposite v right u thrice y and a run o around w left s thrice y 
look o left s thrice y and a turn o around w left s thrice y 
run o opposite v left s twice x after b walk o around w left s twice x 
turn o opposite v right u after b walk o 
run o twice x and a run o opposite v right u twice x 
turn o opposite v right u thrice y after b turn o opposite v left s 
turn o left s thrice y after b look o opposite v left s twice x 
jump o 
look o opposite v left s after b look o around w right u thrice y 
turn o around w right u thrice y after b run o around w right u thrice y 
run o left s and a look o opposite v left s 
run o right u and a run o around w right u thrice y 
run o left s twice x after b run o left s thrice y 
run o around w left s thrice y after b walk o opposite v right u twice x 
jump o 
walk o opposite v left s thrice y after b look o opposite v left s thrice y 
look o left s thrice y after b turn o around w left s twice x 
look o right u twice x after b look o opposite v right u 
jump o 
turn o opposite v right u twice x and a turn o around w left s 
look o right u twice x and a run o left s 
look o twice x and a turn o opposite v left s thrice y 
run o and a turn o around w left s thrice y 
run o after b walk o around w left s thrice y 
turn o right u twice x after b look o twice x 
look o around w left s after b walk o around w left s twice x 
look o right u twice x and a turn o left s thrice y 
jump o 
run o right u thrice y and a look o around w right u thrice y 
run o thrice y after b look o around w right u twice x 
jump o 
walk o opposite v right u thrice y and a walk o left s thrice y 
turn o around w left s thrice y and a walk o opposite v right u twice x 
turn o around w left s thrice y after b look o around w right u 
look o right u thrice y and a run o left s twice x 
run o right u twice x after b run o opposite v left s thrice y 
jump o 
walk o and a look o around w right u 
turn o right u thrice y and a turn o left s 
walk o left s and a run o right u 
run o left s twice x after b look o thrice y 
turn o around w left s after b walk o opposite v left s 
turn o around w right u and a look o around w left s 
turn o right u twice x and a run o opposite v left s thrice y 
look o left s twice x after b walk o opposite v right u thrice y 
look o right u thrice y after b turn o left s thrice y 
run o around w left s thrice y after b run o right u thrice y 
walk o right u thrice y and a look o opposite v left s 
run o opposite v right u thrice y after b turn o around w right u twice x 
run o opposite v right u and a run o 
walk o left s twice x and a run o around w right u twice x 
run o around w left s thrice y after b walk o around w left s 
walk o around w right u thrice y after b run o opposite v right u twice x 
turn o around w right u twice x and a turn o opposite v right u 
run o opposite v left s and a turn o left s 
walk o left s and a run o around w right u 
look o left s thrice y after b run o left s twice x 
walk o right u and a turn o around w left s 
walk o twice x after b run o left s 
run o after b run o opposite v right u 
walk o right u thrice y and a look o around w left s twice x 
look o opposite v left s twice x after b turn o right u 
look o opposite v left s after b turn o around w left s 
turn o left s after b walk o opposite v left s 
look o right u twice x and a walk o opposite v left s 
look o opposite v left s twice x and a turn o opposite v left s thrice y 
turn o right u thrice y and a look o left s twice x 
look o left s thrice y and a turn o around w right u 
jump o 
run o opposite v right u twice x after b run o around w left s twice x 
walk o thrice y and a walk o around w right u twice x 
turn o opposite v left s after b turn o right u 
turn o opposite v right u thrice y after b walk o 
walk o opposite v left s twice x and a walk o left s 
walk o around w right u and a turn o right u 
walk o around w right u thrice y after b turn o right u thrice y 
walk o around w left s after b run o right u thrice y 
jump o 
look o twice x and a run o twice x 
walk o opposite v right u twice x and a look o around w left s thrice y 
run o opposite v left s after b turn o around w left s twice x 
walk o left s and a turn o opposite v right u 
look o around w left s thrice y after b walk o left s 
turn o opposite v left s twice x and a look o around w left s thrice y 
walk o around w right u twice x and a walk o around w right u thrice y 
look o left s thrice y after b run o 
run o thrice y and a walk o left s thrice y 
look o opposite v right u after b turn o right u thrice y 
run o opposite v right u twice x and a turn o around w right u 
jump o 
look o opposite v left s after b turn o opposite v right u thrice y 
turn o opposite v right u twice x and a look o 
jump o 
turn o around w right u thrice y after b look o left s twice x 
run o around w left s twice x and a turn o opposite v left s thrice y 
walk o around w left s twice x after b run o left s thrice y 
walk o around w left s twice x and a walk o left s twice x 
turn o opposite v left s thrice y and a turn o left s thrice y 
look o thrice y after b turn o opposite v left s 
run o around w left s after b walk o right u 
turn o around w right u and a look o around w right u thrice y 
turn o around w right u and a walk o opposite v left s 
look o left s twice x and a walk o around w left s 
turn o around w right u twice x and a walk o left s 
turn o opposite v right u twice x and a walk o left s thrice y 
run o around w right u thrice y after b walk o opposite v right u thrice y 
jump o 
look o around w left s and a turn o around w left s thrice y 
look o opposite v left s and a look o 
walk o right u twice x after b turn o opposite v right u twice x 
run o right u thrice y and a look o left s thrice y 
jump o 
look o after b run o opposite v left s twice x 
turn o left s and a walk o thrice y 
turn o opposite v left s thrice y and a look o opposite v right u twice x 
turn o opposite v right u thrice y after b turn o around w left s thrice y 
walk o opposite v left s and a walk o around w left s thrice y 
run o opposite v left s after b turn o opposite v right u twice x 
turn o opposite v right u after b run o 
turn o opposite v right u thrice y and a run o opposite v right u twice x 
turn o opposite v left s twice x after b turn o around w left s thrice y 
walk o opposite v left s and a run o around w right u twice x 
walk o opposite v left s and a turn o left s twice x 
jump o 
walk o right u twice x and a look o around w right u twice x 
walk o left s and a walk o around w left s thrice y 
run o around w left s twice x and a turn o opposite v left s twice x 
walk o left s thrice y and a run o right u 
jump o 
look o right u thrice y and a run o around w left s 
turn o opposite v left s and a run o right u thrice y 
walk o left s twice x after b look o 
run o right u twice x and a walk o around w right u twice x 
look o left s and a walk o right u twice x 
turn o right u thrice y and a look o around w left s thrice y 
jump o 
walk o opposite v right u thrice y and a run o right u thrice y 
turn o left s thrice y after b look o right u twice x 
walk o around w left s thrice y after b walk o opposite v right u 
run o opposite v right u twice x after b walk o opposite v right u twice x 
run o opposite v right u and a walk o thrice y 
look o around w right u thrice y and a walk o 
walk o around w right u twice x after b walk o opposite v left s thrice y 
turn o opposite v left s twice x and a turn o around w right u twice x 
turn o opposite v left s and a run o around w left s thrice y 
turn o around w left s twice x and a look o around w right u 
turn o opposite v right u and a look o around w right u thrice y 
look o thrice y after b look o around w right u thrice y 
run o opposite v right u and a turn o around w right u 
run o opposite v left s thrice y after b turn o right u 
run o twice x after b look o opposite v left s twice x 
look o and a run o left s thrice y 
run o opposite v left s thrice y and a turn o left s twice x 
look o left s after b look o opposite v left s thrice y 
walk o left s thrice y and a run o opposite v left s twice x 
turn o left s after b walk o around w right u twice x 
walk o and a turn o opposite v right u twice x 
look o around w left s and a walk o opposite v left s 
look o opposite v right u thrice y after b walk o opposite v right u twice x 
run o left s after b turn o around w right u thrice y 
turn o opposite v right u thrice y after b run o around w right u 
turn o opposite v right u twice x and a walk o left s twice x 
turn o opposite v left s after b turn o opposite v left s twice x 
jump o 
walk o around w left s after b look o opposite v left s twice x 
walk o around w left s and a turn o right u 
look o opposite v left s thrice y and a walk o around w left s 
look o thrice y after b walk o right u 
look o twice x after b turn o opposite v left s thrice y 
run o around w left s twice x and a look o left s twice x 
look o opposite v right u and a turn o opposite v right u twice x 
run o around w left s and a walk o opposite v left s thrice y 
walk o right u thrice y after b run o twice x 
look o left s thrice y and a walk o opposite v right u thrice y 
run o opposite v left s twice x and a look o opposite v left s 
look o opposite v left s twice x and a turn o right u twice x 
walk o around w right u twice x and a look o left s 
look o opposite v left s thrice y and a look o opposite v left s 
look o around w right u thrice y and a walk o thrice y 
walk o around w right u twice x after b run o opposite v left s 
look o left s and a walk o left s 
turn o around w left s twice x after b run o 
jump o 
jump o 
look o right u thrice y after b look o around w left s thrice y 
jump o 
turn o right u thrice y and a run o twice x 
walk o opposite v right u and a walk o opposite v right u 
turn o opposite v left s thrice y and a turn o around w right u thrice y 
walk o twice x and a walk o right u 
turn o right u thrice y and a walk o right u 
turn o around w left s and a walk o left s 
walk o left s thrice y after b turn o left s thrice y 
run o right u after b look o around w right u thrice y 
look o around w right u thrice y after b run o thrice y 
run o around w left s after b turn o around w left s twice x 
look o opposite v right u thrice y after b look o opposite v left s thrice y 
walk o right u thrice y and a walk o opposite v right u thrice y 
turn o around w left s twice x after b walk o opposite v left s thrice y 
look o opposite v right u thrice y and a turn o opposite v left s twice x 
look o right u twice x after b walk o opposite v left s 
turn o right u twice x after b walk o opposite v left s thrice y 
walk o around w right u twice x and a run o around w right u thrice y 
walk o right u twice x after b run o left s 
walk o right u thrice y and a run o around w right u 
turn o opposite v right u and a look o opposite v left s thrice y 
jump o 
walk o left s thrice y and a run o right u thrice y 
run o left s thrice y after b walk o opposite v right u twice x 
walk o thrice y after b look o right u thrice y 
look o left s thrice y and a walk o thrice y 
walk o after b run o left s twice x 
jump o 
run o opposite v right u thrice y after b walk o opposite v left s twice x 
walk o left s thrice y after b walk o thrice y 
look o opposite v right u after b run o left s thrice y 
turn o left s twice x after b look o right u 
walk o opposite v right u twice x after b turn o around w left s 
look o around w left s thrice y after b look o opposite v left s twice x 
walk o right u twice x and a look o opposite v left s twice x 
look o left s twice x and a walk o opposite v right u 
walk o opposite v left s twice x and a turn o right u thrice y 
walk o twice x after b look o left s thrice y 
run o left s twice x after b look o around w left s thrice y 
run o twice x and a run o opposite v left s twice x 
walk o opposite v left s thrice y and a look o left s thrice y 
look o around w right u thrice y after b walk o 
look o around w right u twice x and a turn o left s 
turn o opposite v right u and a look o left s thrice y 
walk o opposite v left s and a look o opposite v right u twice x 
run o around w left s thrice y after b walk o twice x 
walk o right u twice x and a turn o around w right u 
walk o around w left s thrice y after b walk o around w right u 
run o right u and a run o right u thrice y 
turn o around w right u thrice y after b turn o opposite v left s 
look o and a look o around w right u thrice y 
turn o around w left s twice x after b look o around w right u thrice y 
run o thrice y and a turn o opposite v left s 
run o left s twice x after b look o opposite v left s twice x 
jump o 
run o after b look o around w left s twice x 
look o around w left s after b walk o opposite v right u twice x 
jump o 
look o opposite v right u and a walk o 
walk o opposite v right u twice x after b walk o right u 
turn o around w right u after b run o right u 
run o thrice y after b run o around w left s twice x 
run o around w left s thrice y and a run o opposite v left s thrice y 
run o around w right u twice x and a walk o around w left s 
run o around w right u thrice y after b turn o opposite v left s 
turn o right u thrice y after b run o opposite v right u twice x 
walk o opposite v left s after b run o left s thrice y 
walk o opposite v right u twice x and a walk o left s twice x 
look o thrice y after b look o around w left s thrice y 
turn o around w left s twice x and a walk o left s twice x 
look o left s after b look o opposite v right u thrice y 
look o opposite v right u twice x and a turn o opposite v right u 
look o opposite v left s thrice y and a look o around w right u twice x 
look o opposite v right u and a walk o right u thrice y 
jump o 
jump o 
look o opposite v left s twice x after b run o 
run o right u and a look o twice x 
run o right u twice x after b walk o opposite v left s thrice y 
run o around w left s twice x and a look o around w left s 
run o twice x and a run o thrice y 
walk o around w right u twice x after b walk o opposite v left s twice x 
run o opposite v right u thrice y after b turn o opposite v left s twice x 
walk o opposite v left s thrice y after b walk o opposite v left s thrice y 
run o around w left s thrice y after b run o around w right u twice x 
turn o left s thrice y after b run o right u twice x 
look o right u thrice y after b walk o opposite v left s thrice y 
walk o left s thrice y and a walk o around w left s twice x 
jump o 
look o left s thrice y and a run o around w left s thrice y 
jump o 
look o left s thrice y and a walk o left s twice x 
run o opposite v right u thrice y and a run o opposite v left s 
walk o left s twice x and a run o opposite v left s twice x 
jump o 
walk o opposite v left s after b look o left s 
run o twice x after b look o right u twice x 
walk o around w left s twice x and a look o opposite v right u twice x 
turn o left s after b look o right u 
run o around w right u after b look o around w right u 
jump o 
look o opposite v left s twice x after b walk o opposite v right u thrice y 
turn o around w right u thrice y after b turn o opposite v right u thrice y 
look o thrice y and a run o 
turn o opposite v right u twice x and a look o opposite v left s thrice y 
run o opposite v right u twice x after b turn o around w left s thrice y 
look o left s twice x after b turn o around w right u thrice y 
look o opposite v left s twice x and a turn o left s thrice y 
walk o opposite v right u twice x and a look o left s thrice y 
run o after b walk o 
look o opposite v right u thrice y and a walk o left s 
walk o around w right u and a walk o around w left s twice x 
walk o right u twice x after b look o left s thrice y 
look o right u after b run o opposite v right u twice x 
walk o around w left s twice x and a turn o opposite v right u twice x 
walk o left s twice x after b run o 
turn o right u twice x after b turn o around w right u thrice y 
jump o 
look o left s after b turn o opposite v left s twice x 
look o opposite v right u twice x after b run o 
look o around w left s and a walk o right u 
walk o left s after b walk o opposite v right u thrice y 
look o left s twice x and a run o right u thrice y 
jump o 
run o right u after b turn o left s 
look o around w right u thrice y and a look o 
turn o left s and a run o opposite v right u thrice y 
walk o left s twice x after b run o twice x 
turn o right u thrice y after b look o opposite v left s 
walk o around w right u after b look o around w left s twice x 
run o around w left s twice x after b look o right u 
run o thrice y and a run o around w right u thrice y 
run o opposite v left s thrice y and a run o around w left s thrice y 
run o opposite v left s thrice y after b turn o around w left s twice x 
run o thrice y after b walk o around w right u twice x 
run o around w right u after b run o around w left s twice x 
jump o 
run o and a run o thrice y 
run o left s twice x and a run o around w left s thrice y 
turn o opposite v left s twice x and a walk o opposite v right u 
turn o opposite v right u and a look o opposite v right u 
jump o 
look o opposite v right u thrice y after b run o around w right u twice x 
run o left s thrice y after b turn o around w left s twice x 
look o opposite v left s twice x and a look o opposite v left s 
run o thrice y after b look o twice x 
look o opposite v right u thrice y and a walk o around w left s 
walk o around w left s and a look o around w right u twice x 
walk o opposite v right u twice x after b walk o right u twice x 
jump o 
turn o right u and a look o 
jump o 
look o left s twice x and a run o left s twice x 
turn o around w left s after b turn o right u twice x 
walk o around w right u after b run o opposite v right u twice x 
look o around w right u twice x after b run o left s 
turn o around w left s thrice y and a look o opposite v right u 
jump o 
look o opposite v right u and a walk o opposite v left s 
turn o around w right u twice x after b look o right u twice x 
walk o opposite v left s twice x after b walk o around w right u thrice y 
run o right u thrice y and a walk o left s thrice y 
jump o 
turn o opposite v left s twice x after b run o 
walk o opposite v right u thrice y after b turn o left s 
turn o around w right u after b turn o left s thrice y 
jump o 
turn o around w left s twice x and a look o thrice y 
look o around w right u twice x after b turn o left s 
walk o around w left s and a turn o left s 
turn o opposite v right u after b turn o opposite v left s 
walk o around w right u and a turn o opposite v left s twice x 
turn o opposite v right u thrice y after b turn o left s twice x 
turn o around w right u after b turn o opposite v left s thrice y 
turn o right u twice x after b run o right u twice x 
run o opposite v left s and a turn o right u twice x 
walk o opposite v right u thrice y and a look o opposite v left s 
turn o right u twice x after b look o around w right u thrice y 
turn o around w right u thrice y after b turn o opposite v right u 
look o thrice y after b run o around w right u twice x 
run o opposite v left s twice x after b run o twice x 
walk o right u after b walk o left s thrice y 
turn o opposite v right u and a walk o 
look o around w left s twice x after b walk o opposite v left s 
turn o around w right u thrice y after b run o left s 
turn o right u twice x and a look o opposite v right u 
turn o around w left s twice x after b look o right u 
look o left s thrice y and a look o left s thrice y 
look o opposite v right u twice x and a run o left s 
run o around w right u thrice y after b look o left s twice x 
run o around w right u thrice y and a turn o around w left s 
walk o right u thrice y and a look o right u thrice y 
walk o right u and a look o right u twice x 
look o opposite v right u thrice y and a run o 
look o thrice y after b run o left s 
walk o thrice y after b look o twice x 
run o left s thrice y after b look o opposite v right u thrice y 
walk o around w left s thrice y and a run o around w left s twice x 
